/**
 * Centralized, replaceable image configuration.
 *
 * Images are self-hosted SVG placeholders in /public/img (generated by
 * scripts/gen-placeholders.mjs). They always load — no external image host — so
 * the site is fast and reliable everywhere, including mainland China, and on any
 * static host (Cloudflare Pages, etc.).
 *
 * To replace with real photography before launch, either:
 *   1) drop a same-named file into /public/img (e.g. beijing.jpg) and update the
 *      extension below, or
 *   2) point `src` at your own CDN URL and add its domain to next.config.mjs.
 *
 * Every entry includes intrinsic dimensions to prevent layout shift, plus
 * descriptive alt text for accessibility.
 */
export type SiteImage = {
  src: string;
  alt: string;
  width: number;
  height: number;
};

const LANDSCAPE = { width: 1600, height: 1067 };
const HERO = { width: 2000, height: 1250 };
const SQUARE = { width: 800, height: 800 };
const PORTRAIT = { width: 700, height: 800 };

// key -> { alt, dimensions }. `src` is derived as /img/<key>.svg.
const META = {
  heroHome: { alt: "Travelers exploring a contemporary Chinese city at dusk", ...HERO },
  ctaFinal: { alt: "A high-speed train crossing the Chinese countryside", ...HERO },

  beijing: { alt: "Beijing — imperial landmarks and hutong lanes", ...LANDSCAPE },
  shanghai: { alt: "Shanghai — the Pudong skyline over the river", ...LANDSCAPE },
  xian: { alt: "Xi'an — the ancient city wall at twilight", ...LANDSCAPE },
  chengdu: { alt: "Chengdu — tea houses, pandas and late-night eating", ...LANDSCAPE },
  chongqing: { alt: "Chongqing — stacked neon buildings on the hillsides at night", ...LANDSCAPE },
  zhangjiajie: { alt: "Zhangjiajie — mist drifting between sandstone pillars", ...LANDSCAPE },
  yunnan: { alt: "Yunnan — terraced fields and mountains", ...LANDSCAPE },
  xinjiang: { alt: "Xinjiang — desert dunes and distant mountains", ...LANDSCAPE },
  guilin: { alt: "Guilin — karst peaks along the Li River", ...LANDSCAPE },
  tibet: { alt: "Tibet — the Potala Palace beneath a clear plateau sky", ...LANDSCAPE },

  tripEssentials: { alt: "China Essentials — a classic streetscape blending old and new China", ...LANDSCAPE },
  tripChengduNight: { alt: "Chengdu After Dark — steam rising from a night-market hotpot", ...LANDSCAPE },
  tripWildYunnan: { alt: "Wild Yunnan — a footpath winding through green hills", ...LANDSCAPE },
  tripBeijingStopover: { alt: "Beijing Stopover — a quiet hutong alleyway", ...LANDSCAPE },
  tripHighSpeed: { alt: "China by High-Speed Rail — a train at a modern station platform", ...LANDSCAPE },
  tripChongqing: { alt: "Chongqing City Rush — the layered skyline reflected in the river", ...LANDSCAPE },
  tripZhangjiajie: { alt: "Zhangjiajie & Beyond — a viewing platform among the peaks", ...LANDSCAPE },
  tripSilkRoad: { alt: "Silk Road West — camels crossing desert dunes", ...LANDSCAPE },
  tripTibet: { alt: "Tibet: Roof of the World — monasteries and high plateau", ...LANDSCAPE },
  tripChengdu: { alt: "Chengdu & Pandas — giant pandas and Sichuan food", ...LANDSCAPE },

  spotlightTibet: { alt: "Tibet — the roof of the world, monasteries and Himalayan peaks", ...HERO },
  spotlightChengdu: { alt: "Chengdu — giant pandas, tea houses and fiery hotpot", ...HERO },

  hostLina: { alt: "Portrait of Lina, a Chengdu food host", ...PORTRAIT },
  hostEric: { alt: "Portrait of Eric, a Beijing history guide", ...PORTRAIT },
  hostMia: { alt: "Portrait of Mia, a Yunnan trip designer", ...PORTRAIT },
  hostTashi: { alt: "Portrait of Tashi, a Tibetan plateau specialist", ...PORTRAIT },

  articlePay: { alt: "Paying with a phone at a Chinese street stall", ...LANDSCAPE },
  articleApps: { alt: "Travel apps on a phone at a cafe table", ...LANDSCAPE },
  articleTrains: { alt: "The interior of a modern Chinese high-speed train", ...LANDSCAPE },
  articleEsim: { alt: "Checking a phone map on a city street", ...LANDSCAPE },
  articleVisa: { alt: "A passport and boarding pass on a wooden surface", ...LANDSCAPE },
  articleSolo: { alt: "A solo traveler with a backpack overlooking a city", ...LANDSCAPE },
  articleDays: { alt: "A travel map and itinerary planning notes", ...LANDSCAPE },
  articleTips: { alt: "Everyday practical details of travel in a Chinese city", ...LANDSCAPE },

  reviewPanda: { alt: "A giant panda eating bamboo", ...SQUARE },
  reviewMarket: { alt: "A colorful night-market food stall", ...SQUARE },
  reviewMountain: { alt: "A traveler photographing mountain scenery", ...SQUARE },
} as const;

export type ImageKey = keyof typeof META;

// Real photos dropped into public/img are recorded here by scripts/scan-photos.mjs
// (runs on build). A key with a real photo uses it; otherwise the SVG placeholder.
import photoManifest from "../../public/img/photo-manifest.json";
const manifest = photoManifest as Record<string, string>;

export const IMAGES = Object.fromEntries(
  Object.entries(META).map(([key, m]) => [
    key,
    { src: `/img/${manifest[key] ?? `${key}.svg`}`, ...m },
  ]),
) as Record<ImageKey, SiteImage>;

export function getImage(key: ImageKey): SiteImage {
  return IMAGES[key];
}
