import type { Trip } from "./types";

/**
 * Mock trip catalog. Realistic sample data for prototyping only — prices,
 * dates, ratings and review counts must be replaced with verified data before
 * launch. Departure dates use 2026 to match the planning window.
 */
export const trips: Trip[] = [
  {
    slug: "china-essentials",
    name: "China Essentials",
    category: "First Time in China",
    style: "Small Group",
    tagline: "The three icons — Beijing, Xi'an and Shanghai — done properly, without the tourist-trap autopilot.",
    durationValue: 8,
    durationUnit: "days",
    route: ["Beijing", "Xi'an", "Shanghai"],
    destinationSlugs: ["beijing", "xian", "shanghai"],
    travelStyleSlugs: ["first-time", "small-group"],
    fromPriceUSD: 1680,
    rating: 4.9,
    reviewCount: 214,
    maxGroupSize: 12,
    activityLevel: "Moderate",
    soloFriendly: true,
    familyFriendly: true,
    departureMonths: [3, 4, 5, 9, 10, 11],
    image: "tripEssentials",
    gallery: ["tripEssentials", "beijing", "xian", "shanghai"],
    bestSeller: true,
    customizable: true,
    highlights: [
      "A quiet-hours visit to the Great Wall at a restored-but-uncrowded section",
      "The Terracotta Warriors with a local archaeologist as your guide",
      "A hutong breakfast crawl most tour groups never see",
      "High-speed rail between every city — no internal flights, no airport queues",
    ],
    whoFor: [
      "First-time visitors who want the icons without a rushed coach-tour feel",
      "Travelers who care about food and street-level culture",
      "Solo travelers and couples comfortable in a small group",
    ],
    itinerary: [
      { day: 1, title: "Arrive in Beijing", summary: "Airport pickup, hotel check-in and an evening orientation walk with your guide.", highlights: ["Meet your group", "Evening dumpling dinner"], meals: "Dinner", accommodation: "Boutique courtyard hotel" },
      { day: 2, title: "Great Wall, quiet section", summary: "A full day at a restored-but-peaceful stretch of the Wall, away from the crowds.", highlights: ["Cable car up, walk down", "Picnic lunch on the ramparts"], meals: "Breakfast, lunch", accommodation: "Boutique courtyard hotel" },
      { day: 3, title: "Forbidden City & hutongs", summary: "The imperial core in the morning, then a walking food crawl through the old lanes.", highlights: ["Forbidden City", "Hutong breakfast crawl"], meals: "Breakfast", accommodation: "Boutique courtyard hotel" },
      { day: 4, title: "High-speed rail to Xi'an", summary: "Glide south by bullet train, then an evening on the city wall.", highlights: ["High-speed rail", "City wall at sunset"], meals: "Breakfast", accommodation: "Design hotel near the Bell Tower" },
      { day: 5, title: "Terracotta Warriors", summary: "A morning with the warriors guided by a local archaeologist, then the Muslim Quarter for lunch.", highlights: ["Terracotta Army", "Muslim Quarter street food"], meals: "Breakfast, lunch", accommodation: "Design hotel near the Bell Tower" },
      { day: 6, title: "High-speed rail to Shanghai", summary: "Travel east and arrive into China's most future-facing city.", highlights: ["High-speed rail", "Bund evening walk"], meals: "Breakfast", accommodation: "Riverside design hotel" },
      { day: 7, title: "Shanghai, old and new", summary: "The former French Concession by day, rooftop skyline by night.", highlights: ["French Concession", "Rooftop drinks"], meals: "Breakfast", accommodation: "Riverside design hotel" },
      { day: 8, title: "Departure", summary: "Free morning and airport transfer whenever your flight leaves.", highlights: ["Free time", "Airport transfer"], meals: "Breakfast" },
    ],
    included: [
      "7 nights boutique accommodation",
      "All high-speed rail between cities",
      "English-speaking local guides in each city",
      "Daily breakfast and selected meals",
      "All listed entrance tickets",
      "Airport transfers",
    ],
    notIncluded: ["International flights", "China visa or transit permit", "Travel insurance", "Most lunches and dinners", "Personal expenses and tips"],
    accommodation: "Hand-picked boutique and design hotels rated 4 stars or above, chosen for location and character over chain uniformity.",
    transport: "City-to-city travel is entirely by high-speed rail in second class (first-class upgrade available). Private vehicles for day excursions.",
    cancellation: "Free cancellation up to 30 days before departure. 50% refund up to 14 days before. See full booking conditions for details.",
    hostSlug: "eric",
    departures: [
      { date: "2026-03-21", status: "available", priceUSD: 1680 },
      { date: "2026-04-18", status: "limited", priceUSD: 1740 },
      { date: "2026-05-16", status: "guaranteed", priceUSD: 1740 },
      { date: "2026-09-19", status: "available", priceUSD: 1760 },
      { date: "2026-10-17", status: "limited", priceUSD: 1820 },
    ],
    faqs: [
      { question: "Do I need a visa for this trip?", answer: "Most travelers need a tourist (L) visa or may qualify for a visa-free transit policy depending on nationality and routing. We send a personalized checklist after booking, but always confirm current rules with your nearest Chinese embassy." },
      { question: "How big is the group?", answer: "Maximum 12 travelers. The average group is 8–10, with a single local guide per city." },
      { question: "Is this trip good for solo travelers?", answer: "Yes — roughly a third of travelers join solo. A single supplement applies for a private room, or we can pair same-gender roommates on request." },
    ],
  },
  {
    slug: "chengdu-after-dark",
    name: "Chengdu After Dark",
    category: "Food & Nightlife",
    style: "Food & Nightlife",
    tagline: "A four-hour evening crawl through Chengdu's night markets, hotpot dens and tea-house backstreets with a local food host.",
    durationValue: 4,
    durationUnit: "hours",
    route: ["Chengdu"],
    destinationSlugs: ["chengdu"],
    travelStyleSlugs: ["food-nightlife", "city-experience"],
    fromPriceUSD: 68,
    rating: 4.95,
    reviewCount: 389,
    maxGroupSize: 8,
    activityLevel: "Easy",
    soloFriendly: true,
    familyFriendly: true,
    departureMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    image: "tripChengduNight",
    gallery: ["tripChengduNight", "chengdu", "reviewMarket"],
    bestSeller: true,
    customizable: false,
    highlights: [
      "Six to eight tastings across markets, stalls and a family hotpot spot",
      "A spice-level walkthrough so you order like a local, not a tourist",
      "A late tea house where locals play mahjong past midnight",
    ],
    whoFor: ["Food-led travelers", "Evening arrivals with one night in Chengdu", "Anyone nervous about ordering Sichuan food solo"],
    itinerary: [
      { day: 1, title: "Meet at the night market", summary: "Gather at dusk and start with skewers and a cold-noodle warm-up.", highlights: ["Street skewers", "Spice-level briefing"] },
      { day: 2, title: "Hotpot with a local family", summary: "Sit down for the main event — mala broth, the dipping-sauce ritual and plenty of stories.", highlights: ["Family hotpot", "Sauce bar masterclass"] },
      { day: 3, title: "Tea house & mahjong lanes", summary: "Wind down in a backstreet tea house where the night is just getting going.", highlights: ["Late tea house", "Mahjong watching"] },
    ],
    included: ["Local food host for 4 hours", "All food tastings (6–8 stops)", "One round of tea or a local drink", "Spice-level guidance"],
    notIncluded: ["Hotel pickup", "Additional alcoholic drinks", "Gratuities"],
    accommodation: "Not applicable — this is an evening experience.",
    transport: "On foot, with one short metro or taxi hop covered by your host.",
    cancellation: "Free cancellation up to 24 hours before the experience.",
    hostSlug: "lina",
    departures: [
      { date: "2026-06-30", status: "available", priceUSD: 68 },
      { date: "2026-07-01", status: "available", priceUSD: 68 },
      { date: "2026-07-02", status: "limited", priceUSD: 68 },
    ],
    faqs: [
      { question: "How spicy is the food?", answer: "Sichuan food is famously bold, but your host adjusts every stop and always offers milder options. Tell us your limit and we'll order around it." },
      { question: "Can you cater to dietary needs?", answer: "Vegetarian routing is possible with advance notice. Strict vegan and some allergy needs are harder with hotpot — message us first and we'll be honest about what works." },
    ],
  },
  {
    slug: "wild-yunnan",
    name: "Wild Yunnan",
    category: "Mountains & Nature",
    style: "Small Group",
    tagline: "From Kunming's lakes to Shangri-La's high meadows — old towns, tea hills and Himalayan foothills at an unhurried pace.",
    durationValue: 9,
    durationUnit: "days",
    route: ["Kunming", "Dali", "Shaxi", "Shangri-La"],
    destinationSlugs: ["yunnan"],
    travelStyleSlugs: ["mountains-nature", "small-group", "slow-local"],
    fromPriceUSD: 2150,
    rating: 4.9,
    reviewCount: 156,
    maxGroupSize: 10,
    activityLevel: "Active",
    soloFriendly: true,
    familyFriendly: false,
    departureMonths: [3, 4, 5, 6, 9, 10],
    image: "tripWildYunnan",
    gallery: ["tripWildYunnan", "yunnan"],
    bestSeller: false,
    customizable: true,
    highlights: [
      "A walking morning around Dali's old town and Erhai Lake",
      "An overnight in tiny Shaxi, a restored caravan town on the old Tea Horse Road",
      "Tibetan-Yunnan monasteries and meadows around Shangri-La",
    ],
    whoFor: ["Active travelers who like walking and altitude", "Photographers and slow-travel fans", "Travelers wanting a non-obvious second China trip"],
    itinerary: [
      { day: 1, title: "Arrive Kunming", summary: "Land in the 'spring city' and settle in.", highlights: ["Welcome dinner"], meals: "Dinner", accommodation: "Garden hotel" },
      { day: 2, title: "Kunming to Dali", summary: "Travel west to lakeside Dali and its old town walls.", highlights: ["High-speed rail", "Old town walk"], meals: "Breakfast", accommodation: "Courtyard inn" },
      { day: 3, title: "Erhai Lake & villages", summary: "Cycle and walk the lakeshore, stopping in Bai villages.", highlights: ["Lakeside cycling", "Bai village lunch"], meals: "Breakfast, lunch", accommodation: "Courtyard inn" },
      { day: 4, title: "Into Shaxi", summary: "Drive the back roads to the restored caravan town of Shaxi.", highlights: ["Tea Horse Road", "Sideng market square"], meals: "Breakfast", accommodation: "Heritage inn" },
      { day: 5, title: "Shaxi valley walk", summary: "A gentle valley hike between hamlets and terraced fields.", highlights: ["Valley hike", "Local farmhouse lunch"], meals: "Breakfast, lunch", accommodation: "Heritage inn" },
      { day: 6, title: "Climb to Shangri-La", summary: "Ascend onto the plateau; take it slow as the altitude rises.", highlights: ["Scenic drive", "Old town evening"], meals: "Breakfast", accommodation: "Tibetan-style lodge" },
      { day: 7, title: "Monasteries & meadows", summary: "Visit Songzanlin Monastery and walk the high meadows.", highlights: ["Songzanlin Monastery", "Meadow walk"], meals: "Breakfast, lunch", accommodation: "Tibetan-style lodge" },
      { day: 8, title: "Plateau free day", summary: "Optional day hike or a slow day with tea and views.", highlights: ["Optional hike", "Free time"], meals: "Breakfast", accommodation: "Tibetan-style lodge" },
      { day: 9, title: "Departure", summary: "Transfer to Shangri-La airport for onward flights.", highlights: ["Airport transfer"], meals: "Breakfast" },
    ],
    included: ["8 nights characterful accommodation", "Internal high-speed rail and private drives", "English-speaking guide throughout", "Daily breakfast and selected meals", "All listed activities and entrance fees"],
    notIncluded: ["Flights to/from Yunnan", "China visa", "Travel insurance", "Some meals", "Tips"],
    accommodation: "Locally owned courtyard inns, a heritage property in Shaxi and a Tibetan-style lodge in Shangri-La.",
    transport: "A mix of high-speed rail, private vehicle on mountain roads, and walking days. One short domestic flight out.",
    cancellation: "Free cancellation up to 45 days before departure given the remote logistics. See booking conditions.",
    hostSlug: "mia",
    departures: [
      { date: "2026-04-11", status: "available", priceUSD: 2150 },
      { date: "2026-05-09", status: "limited", priceUSD: 2210 },
      { date: "2026-09-12", status: "available", priceUSD: 2250 },
      { date: "2026-10-10", status: "limited", priceUSD: 2310 },
    ],
    faqs: [
      { question: "How high do we go?", answer: "Shangri-La sits at around 3,200m. We build in time to acclimatize and keep the first day there gentle, but talk to your doctor if you have heart or lung conditions." },
      { question: "Is this trip suitable for children?", answer: "Because of the altitude and the number of walking days, we recommend this trip for ages 14 and up." },
    ],
  },
  {
    slug: "beijing-stopover",
    name: "Beijing Stopover",
    category: "City Experience",
    style: "Private",
    tagline: "Two private days that turn a layover into a real Beijing — Wall, hutongs and roast duck, on your schedule.",
    durationValue: 2,
    durationUnit: "days",
    route: ["Beijing"],
    destinationSlugs: ["beijing"],
    travelStyleSlugs: ["city-experience", "private"],
    fromPriceUSD: 320,
    rating: 4.85,
    reviewCount: 97,
    maxGroupSize: 6,
    activityLevel: "Easy",
    soloFriendly: true,
    familyFriendly: true,
    departureMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    image: "tripBeijingStopover",
    gallery: ["tripBeijingStopover", "beijing"],
    bestSeller: false,
    customizable: true,
    highlights: ["A private guide and driver both days", "Great Wall in the morning before the crowds", "A roast-duck dinner picked by your guide"],
    whoFor: ["Travelers on a visa-free transit window", "Layovers of 48–72 hours", "Anyone who wants flexibility over a fixed group"],
    itinerary: [
      { day: 1, title: "Wall & old city", summary: "Early Great Wall visit, then the Forbidden City fringe and a hutong wander.", highlights: ["Great Wall", "Hutong walk"], meals: "Lunch", accommodation: "Your choice or we book" },
      { day: 2, title: "Temples & duck", summary: "Temple of Heaven, a tea house, and a roast-duck send-off dinner.", highlights: ["Temple of Heaven", "Roast duck dinner"], meals: "Breakfast" },
    ],
    included: ["Private English-speaking guide (2 days)", "Private vehicle and driver", "Listed entrance tickets", "One lunch and one dinner"],
    notIncluded: ["Accommodation (we can arrange)", "Flights", "Visa or transit permit", "Other meals", "Tips"],
    accommodation: "Not bundled by default — book your own or let us arrange a hotel near the airport express line.",
    transport: "Private vehicle with driver throughout, plus airport transfers on request.",
    cancellation: "Free cancellation up to 7 days before. Flexible re-timing for delayed connecting flights.",
    hostSlug: "eric",
    departures: [
      { date: "2026-06-29", status: "available", priceUSD: 320 },
      { date: "2026-07-03", status: "available", priceUSD: 320 },
      { date: "2026-07-10", status: "available", priceUSD: 320 },
    ],
    faqs: [
      { question: "Will I make my connecting flight?", answer: "We design the two days around your inbound and outbound times and keep buffers for traffic. Share your flight details and we'll plan backwards from departure." },
      { question: "Do I qualify for visa-free transit?", answer: "Many nationalities qualify for visa-free transit in Beijing when continuing to a third country within the allowed window. Rules change, so we confirm eligibility with you before booking." },
    ],
  },
  {
    slug: "china-by-high-speed-rail",
    name: "China by High-Speed Rail",
    category: "First Time in China",
    style: "Small Group",
    tagline: "Five cities, zero internal flights — a sweeping loop from Beijing to Shanghai threaded together by 300km/h trains.",
    durationValue: 12,
    durationUnit: "days",
    route: ["Beijing", "Xi'an", "Chengdu", "Guilin", "Shanghai"],
    destinationSlugs: ["beijing", "xian", "chengdu", "guilin", "shanghai"],
    travelStyleSlugs: ["first-time", "small-group"],
    fromPriceUSD: 2780,
    rating: 4.92,
    reviewCount: 131,
    maxGroupSize: 12,
    activityLevel: "Moderate",
    soloFriendly: true,
    familyFriendly: true,
    departureMonths: [3, 4, 5, 9, 10],
    image: "tripHighSpeed",
    gallery: ["tripHighSpeed", "beijing", "chengdu", "guilin"],
    bestSeller: true,
    customizable: true,
    highlights: ["The Great Wall, Warriors, pandas and karst rivers in one trip", "Every long leg by high-speed rail — see the country roll past", "A Li River cruise through the Guilin karst landscape"],
    whoFor: ["Travelers who want range without airport days", "Train lovers", "Second-timers wanting more than the big three"],
    itinerary: [
      { day: 1, title: "Arrive Beijing", summary: "Welcome and orientation.", highlights: ["Welcome dinner"], meals: "Dinner", accommodation: "Boutique hotel" },
      { day: 2, title: "Great Wall", summary: "A quiet Wall section.", highlights: ["Great Wall"], meals: "Breakfast, lunch", accommodation: "Boutique hotel" },
      { day: 3, title: "Imperial Beijing", summary: "Forbidden City and hutongs.", highlights: ["Forbidden City"], meals: "Breakfast", accommodation: "Boutique hotel" },
      { day: 4, title: "Rail to Xi'an", summary: "Bullet train south.", highlights: ["High-speed rail", "City wall"], meals: "Breakfast", accommodation: "Design hotel" },
      { day: 5, title: "Terracotta Warriors", summary: "Warriors and the Muslim Quarter.", highlights: ["Terracotta Army"], meals: "Breakfast, lunch", accommodation: "Design hotel" },
      { day: 6, title: "Rail to Chengdu", summary: "West to Sichuan.", highlights: ["High-speed rail"], meals: "Breakfast", accommodation: "City hotel" },
      { day: 7, title: "Pandas & tea houses", summary: "Morning at the panda base, afternoon tea-house life.", highlights: ["Panda base", "Tea house"], meals: "Breakfast", accommodation: "City hotel" },
      { day: 8, title: "Rail to Guilin", summary: "South to karst country.", highlights: ["High-speed rail"], meals: "Breakfast", accommodation: "Riverside hotel" },
      { day: 9, title: "Li River cruise", summary: "Cruise the river past the famous peaks.", highlights: ["Li River cruise"], meals: "Breakfast, lunch", accommodation: "Riverside hotel" },
      { day: 10, title: "Rail to Shanghai", summary: "East to the coast.", highlights: ["High-speed rail", "Bund walk"], meals: "Breakfast", accommodation: "Design hotel" },
      { day: 11, title: "Shanghai", summary: "Old and new Shanghai.", highlights: ["French Concession"], meals: "Breakfast", accommodation: "Design hotel" },
      { day: 12, title: "Departure", summary: "Airport transfer.", highlights: ["Airport transfer"], meals: "Breakfast" },
    ],
    included: ["11 nights accommodation", "All high-speed rail legs", "Li River cruise", "Local guides in each city", "Daily breakfast and selected meals", "Listed entrances and transfers"],
    notIncluded: ["International flights", "China visa", "Travel insurance", "Some meals", "Tips"],
    accommodation: "Boutique and design hotels across five cities, each chosen for location near the action.",
    transport: "Long legs by high-speed rail; private vehicles for excursions; one river cruise.",
    cancellation: "Free cancellation up to 30 days before departure. See booking conditions.",
    hostSlug: "eric",
    departures: [
      { date: "2026-03-28", status: "available", priceUSD: 2780 },
      { date: "2026-04-25", status: "limited", priceUSD: 2860 },
      { date: "2026-09-26", status: "available", priceUSD: 2920 },
      { date: "2026-10-17", status: "limited", priceUSD: 2980 },
    ],
    faqs: [
      { question: "Is 12 days too rushed for five cities?", answer: "Because every long leg is by high-speed rail you lose almost no time to airports. Each city gets at least a full day; the pace is moderate, not frantic." },
      { question: "Can I extend in any city?", answer: "Yes. This is a customizable departure — add nights in Chengdu or Shanghai and we'll adjust the rail tickets." },
    ],
  },
  {
    slug: "chongqing-city-rush",
    name: "Chongqing City Rush",
    category: "Big City Energy",
    style: "Private",
    tagline: "Three private days in the most vertical city on earth — cliffside neighborhoods, river light shows and the original mala hotpot.",
    durationValue: 3,
    durationUnit: "days",
    route: ["Chongqing"],
    destinationSlugs: ["chongqing"],
    travelStyleSlugs: ["big-city", "private", "food-nightlife"],
    fromPriceUSD: 540,
    rating: 4.8,
    reviewCount: 64,
    maxGroupSize: 6,
    activityLevel: "Moderate",
    soloFriendly: true,
    familyFriendly: true,
    departureMonths: [1, 2, 3, 4, 5, 9, 10, 11, 12],
    image: "tripChongqing",
    gallery: ["tripChongqing", "chongqing"],
    bestSeller: false,
    customizable: true,
    highlights: ["Ride the cliffside monorail through a building", "A night river cruise under the city's light show", "Authentic Chongqing hotpot, where mala was born"],
    whoFor: ["City and skyline lovers", "Food travelers chasing the real hotpot", "Travelers who like a private, flexible pace"],
    itinerary: [
      { day: 1, title: "Vertical city", summary: "Monorails, escalators and cliffside districts with a private guide.", highlights: ["Liziba monorail", "Hongya Cave at night"], meals: "Lunch", accommodation: "Riverside hotel" },
      { day: 2, title: "River & hotpot", summary: "Daytime river views, evening cruise and a hotpot dinner.", highlights: ["River cruise", "Hotpot dinner"], meals: "Breakfast", accommodation: "Riverside hotel" },
      { day: 3, title: "Backstreets & departure", summary: "A morning in the old quarters before your transfer.", highlights: ["Old quarter walk", "Airport transfer"], meals: "Breakfast" },
    ],
    included: ["2 nights riverside accommodation", "Private guide and driver", "Night river cruise", "One lunch and tickets"],
    notIncluded: ["Flights", "Visa", "Insurance", "Some meals", "Tips"],
    accommodation: "A riverside hotel with skyline views, central to the action.",
    transport: "Private vehicle, plus the city's monorail and a river cruise.",
    cancellation: "Free cancellation up to 14 days before. See booking conditions.",
    hostSlug: "lina",
    departures: [
      { date: "2026-07-04", status: "available", priceUSD: 540 },
      { date: "2026-09-05", status: "available", priceUSD: 560 },
      { date: "2026-10-03", status: "limited", priceUSD: 580 },
    ],
    faqs: [
      { question: "Is Chongqing walkable?", answer: "It's hilly and vertical, with lots of stairs and escalators. Your private pace means we adapt the routing to your fitness, and the driver covers the longer hops." },
    ],
  },
  {
    slug: "zhangjiajie-and-beyond",
    name: "Zhangjiajie & Beyond",
    category: "Mountains & Nature",
    style: "Small Group",
    tagline: "The floating pillars of Zhangjiajie, the waterfalls of Furong and the riverside lanes of Fenghuang — Hunan's wild side.",
    durationValue: 6,
    durationUnit: "days",
    route: ["Zhangjiajie", "Furong", "Fenghuang"],
    destinationSlugs: ["zhangjiajie"],
    travelStyleSlugs: ["mountains-nature", "small-group"],
    fromPriceUSD: 1390,
    rating: 4.88,
    reviewCount: 102,
    maxGroupSize: 12,
    activityLevel: "Active",
    soloFriendly: true,
    familyFriendly: true,
    departureMonths: [4, 5, 6, 9, 10],
    image: "tripZhangjiajie",
    gallery: ["tripZhangjiajie", "zhangjiajie"],
    bestSeller: false,
    customizable: true,
    highlights: ["The sandstone pillars that inspired floating-mountain film scenes", "A glass walkway and the world's highest outdoor lift", "An evening in the lantern-lit riverside town of Fenghuang"],
    whoFor: ["Active travelers and hikers", "Photographers", "Families with older children"],
    itinerary: [
      { day: 1, title: "Arrive Zhangjiajie", summary: "Settle in near the national park.", highlights: ["Welcome dinner"], meals: "Dinner", accommodation: "Park-side hotel" },
      { day: 2, title: "Forest park pillars", summary: "A full day among the famous sandstone columns.", highlights: ["Bailong elevator", "Avatar Hallelujah Mountain"], meals: "Breakfast, lunch", accommodation: "Park-side hotel" },
      { day: 3, title: "Glass bridge & canyon", summary: "Grand Canyon glass bridge and a walk below.", highlights: ["Glass bridge", "Canyon walk"], meals: "Breakfast", accommodation: "Park-side hotel" },
      { day: 4, title: "Furong waterfalls", summary: "Drive to the cliffside waterfall town of Furong.", highlights: ["Furong Town", "Waterfall views"], meals: "Breakfast", accommodation: "Riverside inn" },
      { day: 5, title: "Fenghuang old town", summary: "Continue to the riverside lanes of Fenghuang.", highlights: ["Stilt houses", "Evening lanterns"], meals: "Breakfast", accommodation: "Riverside inn" },
      { day: 6, title: "Departure", summary: "Transfer for onward travel.", highlights: ["Transfer"], meals: "Breakfast" },
    ],
    included: ["5 nights accommodation", "Private vehicle between sights", "English-speaking guide", "Park and cable-car tickets", "Daily breakfast and selected meals"],
    notIncluded: ["Flights or rail to Zhangjiajie", "Visa", "Insurance", "Some meals", "Tips"],
    accommodation: "A comfortable park-side hotel and a riverside inn in Fenghuang.",
    transport: "Private vehicle throughout, plus park shuttles, cable cars and the Bailong elevator.",
    cancellation: "Free cancellation up to 30 days before departure.",
    hostSlug: "mia",
    departures: [
      { date: "2026-04-18", status: "available", priceUSD: 1390 },
      { date: "2026-05-23", status: "limited", priceUSD: 1430 },
      { date: "2026-09-19", status: "available", priceUSD: 1450 },
      { date: "2026-10-10", status: "limited", priceUSD: 1490 },
    ],
    faqs: [
      { question: "How much walking is involved?", answer: "Expect several active days with stairs and uneven paths in the parks. Cable cars and lifts reduce the climbing, but good footwear is essential." },
    ],
  },
  {
    slug: "silk-road-west",
    name: "Silk Road West",
    category: "Ancient Culture",
    style: "Small Group",
    tagline: "Xi'an to Kashgar along the old Silk Road — Buddhist caves, desert oases and the great Sunday bazaar of the far west.",
    durationValue: 11,
    durationUnit: "days",
    route: ["Xi'an", "Lanzhou", "Dunhuang", "Turpan", "Kashgar"],
    destinationSlugs: ["xian", "xinjiang"],
    travelStyleSlugs: ["ancient-culture", "small-group"],
    fromPriceUSD: 3280,
    rating: 4.93,
    reviewCount: 78,
    maxGroupSize: 10,
    activityLevel: "Moderate",
    soloFriendly: true,
    familyFriendly: false,
    departureMonths: [5, 6, 9, 10],
    image: "tripSilkRoad",
    gallery: ["tripSilkRoad", "xinjiang", "xian"],
    bestSeller: false,
    customizable: true,
    highlights: ["The Mogao Grottoes — a thousand years of Buddhist cave art", "Singing-sand dunes and the crescent-moon oasis at Dunhuang", "Kashgar's old town and its legendary Sunday market"],
    whoFor: ["History and culture travelers", "Repeat visitors going deep", "Travelers comfortable with longer overland and rail days"],
    itinerary: [
      { day: 1, title: "Arrive Xi'an", summary: "The Silk Road's eastern start.", highlights: ["City wall"], meals: "Dinner", accommodation: "Design hotel" },
      { day: 2, title: "Warriors & departure point", summary: "Terracotta Warriors and the Great Mosque quarter.", highlights: ["Terracotta Army"], meals: "Breakfast", accommodation: "Design hotel" },
      { day: 3, title: "Rail to Lanzhou", summary: "Along the Yellow River.", highlights: ["High-speed rail", "Riverside walk"], meals: "Breakfast", accommodation: "City hotel" },
      { day: 4, title: "Bingling caves", summary: "A boat trip to cliffside Buddhist grottoes.", highlights: ["Bingling Temple"], meals: "Breakfast, lunch", accommodation: "City hotel" },
      { day: 5, title: "To Dunhuang", summary: "Travel into the desert oasis.", highlights: ["Overnight transit"], meals: "Breakfast", accommodation: "Desert hotel" },
      { day: 6, title: "Mogao Grottoes", summary: "The great cave galleries, then the dunes at sunset.", highlights: ["Mogao Grottoes", "Singing-sand dunes"], meals: "Breakfast", accommodation: "Desert hotel" },
      { day: 7, title: "To Turpan", summary: "Into China's hottest, lowest basin.", highlights: ["Rail journey", "Grape valley"], meals: "Breakfast", accommodation: "Oasis hotel" },
      { day: 8, title: "Turpan oases", summary: "Ancient karez irrigation and ruined cities.", highlights: ["Jiaohe ruins", "Karez wells"], meals: "Breakfast, lunch", accommodation: "Oasis hotel" },
      { day: 9, title: "To Kashgar", summary: "Fly far west to the edge of Central Asia.", highlights: ["Old town walk"], meals: "Breakfast", accommodation: "Old town hotel" },
      { day: 10, title: "Kashgar bazaar", summary: "The famous market and the old quarter's lanes.", highlights: ["Sunday market", "Id Kah square"], meals: "Breakfast", accommodation: "Old town hotel" },
      { day: 11, title: "Departure", summary: "Transfer for your onward flight.", highlights: ["Airport transfer"], meals: "Breakfast" },
    ],
    included: ["10 nights accommodation", "Rail, one internal flight and private drives", "Specialist guides", "Mogao and major site tickets", "Daily breakfast and selected meals"],
    notIncluded: ["International flights", "China visa and any regional permits", "Insurance", "Some meals", "Tips"],
    accommodation: "Comfortable city, desert and old-town hotels across the route.",
    transport: "A mix of high-speed rail, one internal flight to Kashgar, and private vehicles.",
    cancellation: "Free cancellation up to 45 days before departure due to permit and flight logistics.",
    hostSlug: "tashi",
    departures: [
      { date: "2026-05-16", status: "available", priceUSD: 3280 },
      { date: "2026-06-13", status: "limited", priceUSD: 3360 },
      { date: "2026-09-12", status: "available", priceUSD: 3420 },
      { date: "2026-10-03", status: "limited", priceUSD: 3480 },
    ],
    faqs: [
      { question: "Are special permits required?", answer: "Some far-western regions can require extra documentation that changes with current policy. We monitor requirements and handle what's needed once your booking is confirmed." },
      { question: "How long are the travel days?", answer: "A couple of legs are long by design — this is an overland Silk Road journey. We break them with stops and use rail and one flight to keep them comfortable." },
    ],
  },
  {
    slug: "tibet-roof-of-the-world",
    name: "Tibet: Roof of the World",
    category: "Ancient Culture",
    style: "Small Group",
    tagline: "Lhasa's great palaces, monastery debates and a sacred turquoise lake — the Himalayan plateau at a pace that lets you breathe.",
    durationValue: 7,
    durationUnit: "days",
    route: ["Lhasa", "Yamdrok Lake", "Gyantse"],
    destinationSlugs: ["tibet"],
    travelStyleSlugs: ["ancient-culture", "small-group", "mountains-nature"],
    fromPriceUSD: 2480,
    rating: 4.94,
    reviewCount: 88,
    maxGroupSize: 10,
    activityLevel: "Moderate",
    soloFriendly: true,
    familyFriendly: false,
    departureMonths: [4, 5, 6, 9, 10],
    image: "tripTibet",
    gallery: ["tripTibet", "tibet", "spotlightTibet"],
    bestSeller: true,
    strategicPriority: 92,
    tags: ["Tibet", "Lhasa", "Yamdrok", "Monasteries", "High Plateau"],
    searchAliases: ["tibet", "lhasa", "yamdrok", "gyantse", "potala", "tibetan plateau", "himalaya"],
    customizable: true,
    highlights: [
      "The Potala Palace and the pilgrim-filled Jokhang Temple",
      "Monk debates at Sera Monastery",
      "A drive to sacred Yamdrok Lake, framed by snow peaks",
      "Careful altitude pacing with a licensed Tibetan guide throughout",
    ],
    whoFor: [
      "Culture and mountain travelers seeking something profound",
      "Those comfortable at high altitude (with time to acclimatize)",
      "Travelers who want the permits and logistics fully handled",
    ],
    itinerary: [
      { day: 1, title: "Arrive Lhasa — rest", summary: "Meet your guide and take it slow — the first day is for acclimatizing to 3,600m.", highlights: ["Gentle orientation", "Early night"], meals: "Dinner", accommodation: "Tibetan boutique hotel" },
      { day: 2, title: "Potala Palace & Jokhang", summary: "The former winter palace of the Dalai Lamas, then Tibet's holiest temple and the Barkhor kora.", highlights: ["Potala Palace", "Jokhang Temple", "Barkhor circuit"], meals: "Breakfast", accommodation: "Tibetan boutique hotel" },
      { day: 3, title: "Sera & Drepung monasteries", summary: "Two of the great monasteries, including the famous afternoon monk debates at Sera.", highlights: ["Sera monk debates", "Drepung Monastery"], meals: "Breakfast, lunch", accommodation: "Tibetan boutique hotel" },
      { day: 4, title: "Yamdrok Lake", summary: "A spectacular drive over a high pass to the sacred turquoise lake.", highlights: ["Kamba La pass", "Yamdrok Lake"], meals: "Breakfast", accommodation: "Tibetan boutique hotel" },
      { day: 5, title: "Toward Gyantse", summary: "Continue across the plateau to the historic town of Gyantse and its tiered Kumbum stupa.", highlights: ["Gyantse Kumbum", "Plateau scenery"], meals: "Breakfast", accommodation: "Plateau guesthouse" },
      { day: 6, title: "Return to Lhasa", summary: "A scenic return with time for a final wander through the old town.", highlights: ["Old town free time"], meals: "Breakfast", accommodation: "Tibetan boutique hotel" },
      { day: 7, title: "Departure", summary: "Transfer to the station or airport for your onward journey.", highlights: ["Transfer"], meals: "Breakfast" },
    ],
    included: ["6 nights accommodation", "Tibet Travel Permit and arrangements", "Licensed Tibetan guide throughout", "Private vehicle and driver", "Listed monastery and site tickets", "Daily breakfast and selected meals"],
    notIncluded: ["Flights or rail to Lhasa", "China visa", "Travel insurance (required)", "Some meals", "Tips"],
    accommodation: "A characterful Tibetan boutique hotel in Lhasa and a comfortable guesthouse in Gyantse.",
    transport: "Private vehicle across the plateau with a licensed guide; high-altitude railway or flight to reach Lhasa.",
    cancellation: "Free cancellation up to 45 days before departure due to permit lead times. See booking conditions.",
    hostSlug: "tashi",
    departures: [
      { date: "2026-05-16", status: "available", priceUSD: 2480 },
      { date: "2026-06-13", status: "limited", priceUSD: 2540 },
      { date: "2026-09-12", status: "available", priceUSD: 2580 },
      { date: "2026-10-10", status: "limited", priceUSD: 2640 },
    ],
    faqs: [
      { question: "How high is Tibet, and is it safe?", answer: "Lhasa sits above 3,600m. We keep the first day very gentle to help you acclimatize, and your guide watches for altitude symptoms. Talk to your doctor before booking, especially with heart or lung conditions." },
      { question: "Do I need a special permit?", answer: "Yes — Tibet requires a Tibet Travel Permit arranged in advance, and you must travel with a licensed guide. We handle the current permit requirements once your booking is confirmed." },
    ],
  },
  {
    slug: "chengdu-and-pandas",
    name: "Chengdu & Pandas",
    category: "Slow & Local",
    style: "Small Group",
    tagline: "Giant pandas at dawn, tea houses by afternoon and hotpot after dark — the most relaxed four days in China.",
    durationValue: 4,
    durationUnit: "days",
    route: ["Chengdu"],
    destinationSlugs: ["chengdu"],
    travelStyleSlugs: ["slow-local", "small-group", "food-nightlife"],
    fromPriceUSD: 720,
    rating: 4.92,
    reviewCount: 176,
    maxGroupSize: 10,
    activityLevel: "Easy",
    soloFriendly: true,
    familyFriendly: true,
    departureMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    image: "tripChengdu",
    gallery: ["tripChengdu", "chengdu", "reviewPanda"],
    bestSeller: true,
    strategicPriority: 86,
    tags: ["Chengdu", "Panda", "Pandas", "Hotpot", "Sichuan", "Tea House"],
    searchAliases: ["chengdu", "panda", "pandas", "hotpot", "sichuan", "tea house", "mala"],
    customizable: true,
    highlights: [
      "The giant panda base at dawn, when the pandas are most active",
      "A hands-on Sichuan cooking session with a local host",
      "Tea-house culture, ear-cleaners and slow afternoons",
      "A guided hotpot night — the birthplace of mala",
    ],
    whoFor: [
      "First-timers who want a gentle, food-led introduction to China",
      "Families (this is one of our most family-friendly trips)",
      "Anyone who wants to see pandas the right way",
    ],
    itinerary: [
      { day: 1, title: "Arrive Chengdu", summary: "Settle in and take an easy evening stroll through the snack streets with your host.", highlights: ["Jinli snack street", "Welcome dinner"], meals: "Dinner", accommodation: "Central boutique hotel" },
      { day: 2, title: "Pandas at dawn", summary: "An early start at the panda base to see them at their liveliest, then a relaxed afternoon.", highlights: ["Giant panda base", "Tea house afternoon"], meals: "Breakfast", accommodation: "Central boutique hotel" },
      { day: 3, title: "Cook & eat Sichuan", summary: "A market visit and hands-on cooking class, then a guided hotpot night.", highlights: ["Sichuan cooking class", "Hotpot night"], meals: "Breakfast, lunch", accommodation: "Central boutique hotel" },
      { day: 4, title: "Old temples & departure", summary: "A calm morning at Wenshu Monastery before your onward transfer.", highlights: ["Wenshu Monastery", "Transfer"], meals: "Breakfast" },
    ],
    included: ["3 nights central accommodation", "English-speaking local host", "Panda base and site tickets", "Cooking class and hotpot dinner", "Daily breakfast and selected meals", "Airport/station transfers"],
    notIncluded: ["Flights or rail to Chengdu", "China visa", "Travel insurance", "Some meals", "Tips"],
    accommodation: "A central boutique hotel within easy reach of Chengdu's tea houses and snack streets.",
    transport: "Private vehicle for the panda base and transfers; walkable, metro-friendly city otherwise.",
    cancellation: "Free cancellation up to 14 days before departure. See booking conditions.",
    hostSlug: "lina",
    departures: [
      { date: "2026-06-29", status: "available", priceUSD: 720 },
      { date: "2026-07-06", status: "available", priceUSD: 720 },
      { date: "2026-09-07", status: "limited", priceUSD: 740 },
      { date: "2026-10-05", status: "available", priceUSD: 760 },
    ],
    faqs: [
      { question: "What time do we see the pandas?", answer: "We go early, right around opening, because pandas are most active in the cool morning and the base gets busy later. It's an early start but well worth it." },
      { question: "Is this good for kids?", answer: "Yes — it's one of our most family-friendly trips. The pace is easy, the pandas are a hit, and spice levels at meals are always adjustable." },
    ],
  },

  // ==========================================================================
  // Tibet collection — strategic core destination. New inventory: no verified
  // reviews yet (isNew), placeholder pricing, no "guaranteed" departures.
  // ==========================================================================
  {
    slug: "tibet-essentials",
    name: "Tibet Essentials: Lhasa, Yamdrok & Shigatse",
    category: "Ancient Culture",
    style: "Private",
    tagline: "The classic first Tibet journey — Lhasa's palaces, sacred Yamdrok Lake and the monastery town of Shigatse, at an altitude-aware pace.",
    durationValue: 7,
    durationUnit: "days",
    route: ["Lhasa", "Yamdrok Lake", "Gyantse", "Shigatse"],
    destinationSlugs: ["tibet"],
    travelStyleSlugs: ["ancient-culture", "mountains-nature", "first-time", "private"],
    fromPriceUSD: 1980,
    rating: 0,
    reviewCount: 0,
    isNew: true,
    maxGroupSize: 6,
    activityLevel: "Moderate",
    soloFriendly: true,
    familyFriendly: false,
    departureMonths: [4, 5, 6, 9, 10],
    image: "tripTibet",
    gallery: ["tripTibet", "tibet", "spotlightTibet"],
    featured: true,
    strategicPriority: 96,
    customizable: true,
    tags: ["Tibet", "Lhasa", "Yamdrok", "Shigatse", "Monasteries", "High Plateau", "Private Journey"],
    searchAliases: ["tibet", "lhasa", "yamdrok", "shigatse", "gyantse", "potala", "tibetan plateau", "himalaya"],
    highlights: [
      "The Potala Palace and the pilgrim-filled Jokhang Temple",
      "A drive over the Kamba La pass to sacred Yamdrok Lake",
      "Tashilhunpo Monastery in Shigatse",
      "Careful altitude pacing with a licensed local guide",
    ],
    whoFor: ["First-time visitors to Tibet", "Culture and mountain travelers", "Those wanting permits and logistics handled"],
    itinerary: [
      { day: 1, title: "Arrive Lhasa — rest", summary: "Meet your guide and rest to acclimatize to 3,600m.", highlights: ["Gentle orientation"], meals: "Dinner", accommodation: "Lhasa boutique hotel" },
      { day: 2, title: "Potala Palace & Jokhang", summary: "Lhasa's great landmarks and the Barkhor kora.", highlights: ["Potala Palace", "Jokhang Temple"], meals: "Breakfast", accommodation: "Lhasa boutique hotel" },
      { day: 3, title: "Sera & Drepung", summary: "Two great monasteries, including Sera's monk debates.", highlights: ["Sera debates", "Drepung"], meals: "Breakfast", accommodation: "Lhasa boutique hotel" },
      { day: 4, title: "Yamdrok Lake", summary: "Kamba La pass and the sacred turquoise lake.", highlights: ["Yamdrok Lake"], meals: "Breakfast", accommodation: "Gyantse guesthouse" },
      { day: 5, title: "Gyantse to Shigatse", summary: "The tiered Kumbum stupa, then on to Shigatse.", highlights: ["Gyantse Kumbum"], meals: "Breakfast", accommodation: "Shigatse hotel" },
      { day: 6, title: "Tashilhunpo & return", summary: "Shigatse's great monastery, then return toward Lhasa.", highlights: ["Tashilhunpo Monastery"], meals: "Breakfast", accommodation: "Lhasa boutique hotel" },
      { day: 7, title: "Departure", summary: "Transfer to the station or airport.", highlights: ["Transfer"], meals: "Breakfast" },
    ],
    included: ["6 nights accommodation", "Tibet Travel Permit coordination", "Licensed Tibetan guide", "Private vehicle and driver", "Listed site tickets", "Daily breakfast"],
    notIncluded: ["Flights or rail to Lhasa", "China visa", "Travel insurance (required)", "Most meals", "Tips"],
    accommodation: "A characterful boutique hotel in Lhasa and comfortable hotels en route.",
    transport: "Private vehicle with a licensed guide; high-altitude rail or flight to reach Lhasa.",
    cancellation: "Free cancellation up to 45 days before departure due to permit lead times.",
    hostSlug: "tashi",
    departures: [
      { date: "2026-05-16", status: "available", priceUSD: 1980 },
      { date: "2026-06-13", status: "available", priceUSD: 2040 },
      { date: "2026-09-12", status: "limited", priceUSD: 2080 },
    ],
    faqs: [
      { question: "Do I need a permit for Tibet?", answer: "Yes — Tibet requires a Tibet Travel Permit arranged in advance, and you must travel with a licensed guide. We coordinate the required documentation after booking eligibility is confirmed. A permit is not a visa and is separate from your China visa." },
      { question: "How do you handle the altitude?", answer: "Lhasa sits above 3,600m, so the first day is for resting. We pace the itinerary to help you acclimatize. Please consult your doctor before booking." },
    ],
  },
  {
    slug: "8-day-mount-everest",
    name: "8-Day Tour of Mount Everest",
    category: "Mountains & Nature",
    style: "Small Group",
    tagline: "The signature Tibet journey — Lhasa's palaces, sacred Namtso and Yamdrok lakes, Gyantse and Shigatse, and a night beneath the north face of Everest at Rongbuk.",
    durationValue: 8,
    durationUnit: "days",
    route: ["Lhasa", "Namtso", "Yamdrok Lake", "Gyantse", "Shigatse", "Everest Base Camp"],
    destinationSlugs: ["tibet"],
    travelStyleSlugs: ["mountains-nature", "ancient-culture", "small-group"],
    fromPriceUSD: 2280,
    rating: 0,
    reviewCount: 0,
    isNew: true,
    maxGroupSize: 12,
    activityLevel: "Active",
    soloFriendly: true,
    familyFriendly: false,
    departureMonths: [4, 5, 6, 7, 8, 9, 10],
    image: "spotlightTibet",
    gallery: ["spotlightTibet", "tibet", "tripTibet"],
    featured: true,
    strategicPriority: 94,
    customizable: true,
    tags: ["Tibet", "Everest", "EBC", "Rongbuk", "Namtso", "Yamdrok", "Shigatse", "Himalaya"],
    searchAliases: ["everest", "everest base camp", "ebc", "rongbuk", "namtso", "yamdrok", "shigatse", "gyantse", "lhasa", "tibet", "himalaya", "himalayas"],
    highlights: [
      "A night at Everest Base Camp (Rongbuk), with clear-night starfields over the north face",
      "Two of Tibet's three holy lakes — Namtso and Yamdrok",
      "The Gawula Pass viewpoint of five 8,000m peaks",
      "Potala Palace, Jokhang Temple, Tashilhunpo and the Princess Wencheng live show",
    ],
    whoFor: ["Active travelers seeking the Himalaya", "First deep trip into Tibet", "Travelers comfortable with high altitude and long drives"],
    itinerary: [
      { day: 1, title: "Arrive in Lhasa", summary: "Arrive in the 'sunshine city', met with a khata welcome, and rest to adjust to 3,650m — the most important day for acclimatizing.", highlights: ["Airport / railway pickup", "Rest & acclimatize"], accommodation: "4-star oxygen-equipped hotel, Lhasa" },
      { day: 2, title: "Potala Palace, Jokhang & Barkhor", summary: "The Potala Palace and its square, the Medical Hill viewpoint, then the Jokhang Temple and a City Walk on the Barkhor with sweet tea at Ani Sangkhung nunnery.", highlights: ["Potala Palace", "Jokhang Temple", "Barkhor kora"], meals: "Breakfast, dinner", accommodation: "4-star oxygen-equipped hotel, Lhasa" },
      { day: 3, title: "Namtso Lake", summary: "Drive the Beijing–Tibet expressway past the Nyenchen Tanglha range to Namtso, China's third-largest saltwater lake at 4,718m, returning via the 5,190m Laganla Pass (high-altitude challenge certificate).", highlights: ["Nyenchen Tanglha", "Namtso Lake", "Laganla Pass"], meals: "Breakfast", accommodation: "4-star oxygen-equipped hotel, Lhasa" },
      { day: 4, title: "Yamdrok Lake & Gyantse to Shigatse", summary: "Over the Gangbala Pass to turquoise Yamdrok Lake, on to the Karula Glacier and the Palcho (Kumbum) Monastery in Gyantse, arriving in Shigatse.", highlights: ["Yamdrok Lake", "Karula Glacier", "Palcho Monastery"], meals: "Breakfast", accommodation: "4-star hotel, Shigatse" },
      { day: 5, title: "Everest Base Camp", summary: "Cross the Gyatsola Pass into Qomolangma National Park, transfer to the eco-bus to Rongbuk and Everest Base Camp (5,200m marker); visit Rongbuk, the world's highest monastery, and stay overnight in a base-camp tented guesthouse.", highlights: ["Rongbuk Monastery", "Everest Base Camp", "Night-sky views"], meals: "Breakfast", accommodation: "Base-camp tented guesthouse (basic)" },
      { day: 6, title: "Gawula Pass to Shigatse", summary: "Farewell to Everest over the 108-bend Gawula Pass — the viewpoint of five 8,000m peaks (Makalu, Lhotse, Everest, Cho Oyu, Shishapangma) — then back to Shigatse via Lhatse.", highlights: ["Gawula Pass", "Five-peak viewpoint"], meals: "Breakfast", accommodation: "4-star hotel, Shigatse" },
      { day: 7, title: "Tashilhunpo & back to Lhasa", summary: "Tashilhunpo Monastery, seat of the Panchen Lamas, then return to Lhasa on the G318; an intangible-heritage handicraft experience (thangka / incense / calligraphy / carving) and the evening 'Princess Wencheng' live drama.", highlights: ["Tashilhunpo Monastery", "Handicraft experience", "Princess Wencheng show"], meals: "Breakfast, dinner", accommodation: "4-star oxygen-equipped hotel, Lhasa" },
      { day: 8, title: "Departure", summary: "Transfer to the railway station or airport for your onward journey.", highlights: ["Transfer"], meals: "Breakfast" },
    ],
    included: [
      "6 nights 4-star oxygen-equipped hotels + 1 night base-camp tented guesthouse",
      "7 breakfasts and 2 dinners (meals alcohol-free)",
      "Bilingual Chinese/English guide throughout",
      "First-entry tickets to all listed sights (incl. Princess Wencheng show)",
      "Private 7–29 seat vehicle for a 2–12 person MINI group",
      "Tibet Travel Permit coordination; welcome khata, oxygen, glucose, rhodiola and a high-altitude certificate",
      "Zero forced shopping, zero self-pay stops",
    ],
    notIncluded: [
      "Rail or flight to/from Lhasa",
      "China visa",
      "Travel insurance (recommended)",
      "Single-room supplement",
      "Meals not listed, and children's tickets",
      "Personal expenses and anything from force-majeure delays",
    ],
    accommodation: "Six nights in 4-star oxygen-equipped hotels in Lhasa and Shigatse (reference: Tangka, Shambhala, Himalaya Lhasa; Gesar Grand, Shigatse) plus one night in a basic tented guesthouse at Everest Base Camp.",
    transport: "A private 7–29 seat vehicle for a small MINI group of 2–12 travelers with a bilingual guide. Rail or flight to Lhasa is arranged separately.",
    cancellation: "A minimum of 2 travelers is required to operate; if not met we may cancel up to 7 days before departure and refund in full. As Tibet uses chartered vehicles, long-term room blocks and discounted tickets, voluntarily skipping included items is non-refundable.",
    hostSlug: "tashi",
    departures: [
      { date: "2026-05-10", status: "available", priceUSD: 2280 },
      { date: "2026-06-14", status: "available", priceUSD: 2340 },
      { date: "2026-08-16", status: "available", priceUSD: 2380 },
      { date: "2026-09-13", status: "limited", priceUSD: 2380 },
    ],
    faqs: [
      { question: "How high does this trip go, and is it safe?", answer: "Lhasa sits at ~3,650m and Everest Base Camp (Rongbuk) at ~5,200m. Day 1 is for resting, and we pace the route to acclimatize; hotels are oxygen-equipped and we carry oxygen and glucose. Travelers with heart, lung, blood-pressure or serious cold conditions should not enter Tibet — please follow your doctor's advice." },
      { question: "What documents do I need?", answer: "Foreign travelers need a Tibet Travel Permit (separate from, and not the same as, a China visa) and must travel with a licensed guide — we coordinate the permit after booking eligibility is confirmed. Bring your original passport for the Potala Palace and Jokhang Temple." },
      { question: "What are the base-camp conditions?", answer: "The night at Everest Base Camp is in a basic, locally-run tented guesthouse — simple facilities, shared arrangements, and cold at night. It's rustic by design and part of the experience." },
    ],
  },
  {
    slug: "chengdu-to-tibet-by-train",
    name: "Chengdu to Tibet by Train",
    category: "Ancient Culture",
    style: "Private",
    tagline: "Ride one of the world's highest railways from Sichuan onto the plateau, then explore Lhasa, Yamdrok Lake and Shigatse — our two core regions, connected.",
    durationValue: 10,
    durationUnit: "days",
    route: ["Chengdu", "Qinghai-Tibet Railway", "Lhasa", "Yamdrok Lake", "Shigatse"],
    destinationSlugs: ["chengdu", "tibet"],
    travelStyleSlugs: ["slow-local", "ancient-culture", "first-time", "private"],
    fromPriceUSD: 2650,
    rating: 0,
    reviewCount: 0,
    isNew: true,
    maxGroupSize: 8,
    activityLevel: "Moderate",
    soloFriendly: true,
    familyFriendly: false,
    departureMonths: [4, 5, 6, 9, 10],
    image: "tripHighSpeed",
    gallery: ["tripHighSpeed", "tripTibet", "tripChengdu"],
    featured: true,
    strategicPriority: 98,
    customizable: true,
    tags: ["Chengdu", "Tibet", "Train", "Lhasa", "Qinghai-Tibet Railway", "Scenic Railway", "Yamdrok"],
    searchAliases: ["chengdu", "tibet", "train", "railway", "qinghai-tibet railway", "lhasa", "scenic train", "sichuan"],
    highlights: [
      "A scenic ride on the high-altitude Qinghai-Tibet Railway",
      "A gentle start in Chengdu with pandas and tea houses",
      "Lhasa's palaces and monasteries",
      "Sacred Yamdrok Lake and Shigatse",
    ],
    whoFor: ["Travelers who love scenic rail and slow travel", "Those combining our two core regions", "First-timers who want gradual altitude gain"],
    itinerary: [
      { day: 1, title: "Arrive Chengdu", summary: "Settle in with an easy evening walk.", highlights: ["Jinli street"], meals: "Dinner", accommodation: "Chengdu hotel" },
      { day: 2, title: "Pandas & tea houses", summary: "The panda base at dawn and a slow afternoon.", highlights: ["Giant panda base"], meals: "Breakfast", accommodation: "Chengdu hotel" },
      { day: 3, title: "Board the plateau train", summary: "Begin the scenic rail journey toward Lhasa.", highlights: ["Qinghai-Tibet Railway"], meals: "Breakfast", accommodation: "Train (soft sleeper)" },
      { day: 4, title: "Arrive Lhasa — rest", summary: "Arrive acclimatized-ish; rest on arrival.", highlights: ["Rest"], meals: "Breakfast", accommodation: "Lhasa hotel" },
      { day: 5, title: "Potala & Jokhang", summary: "Lhasa's great landmarks and the Barkhor.", highlights: ["Potala Palace", "Jokhang"], meals: "Breakfast", accommodation: "Lhasa hotel" },
      { day: 6, title: "Lhasa monasteries", summary: "Sera and Drepung monasteries.", highlights: ["Sera debates"], meals: "Breakfast", accommodation: "Lhasa hotel" },
      { day: 7, title: "Yamdrok Lake", summary: "Kamba La pass to the sacred lake.", highlights: ["Yamdrok Lake"], meals: "Breakfast", accommodation: "Lhasa hotel" },
      { day: 8, title: "To Shigatse", summary: "Gyantse Kumbum en route to Shigatse.", highlights: ["Gyantse Kumbum"], meals: "Breakfast", accommodation: "Shigatse hotel" },
      { day: 9, title: "Tashilhunpo & return", summary: "Shigatse's monastery, then back to Lhasa.", highlights: ["Tashilhunpo"], meals: "Breakfast", accommodation: "Lhasa hotel" },
      { day: 10, title: "Departure", summary: "Transfer for onward travel.", highlights: ["Transfer"], meals: "Breakfast" },
    ],
    included: ["Chengdu + Tibet accommodation", "Qinghai-Tibet Railway soft-sleeper ticket", "Tibet permits coordination", "Licensed Tibetan guide in Tibet", "Chengdu host", "Private vehicles", "Daily breakfast"],
    notIncluded: ["Flights to Chengdu", "China visa", "Travel insurance (required)", "Most meals", "Tips"],
    accommodation: "Comfortable hotels in Chengdu, Lhasa and Shigatse, plus one night on the train.",
    transport: "Scenic high-altitude railway from Chengdu; private vehicles on the plateau.",
    cancellation: "Free cancellation up to 45 days before departure due to permit and rail lead times.",
    hostSlug: "tashi",
    departures: [
      { date: "2026-05-18", status: "available", priceUSD: 2650 },
      { date: "2026-06-15", status: "available", priceUSD: 2720 },
      { date: "2026-09-14", status: "limited", priceUSD: 2760 },
    ],
    faqs: [
      { question: "Does the train help with altitude?", answer: "The gradual ascent by rail can help some travelers adjust more gently than flying, and the carriages are oxygen-supplemented. We still build in rest time on arrival, and you should consult your doctor." },
      { question: "Why combine Chengdu and Tibet?", answer: "Chengdu is the natural gateway to the plateau and a wonderful, relaxed start. This trip links our two core regions into one journey." },
    ],
  },
  {
    slug: "lhasa-short-stay",
    name: "Lhasa Short Stay",
    category: "City Experience",
    style: "Private",
    tagline: "A focused first taste of Tibet — the Potala Palace, Jokhang Temple and the Barkhor, with time to adjust to the altitude.",
    durationValue: 4,
    durationUnit: "days",
    route: ["Lhasa"],
    destinationSlugs: ["tibet"],
    travelStyleSlugs: ["city-experience", "ancient-culture", "private"],
    fromPriceUSD: 980,
    rating: 0,
    reviewCount: 0,
    isNew: true,
    maxGroupSize: 6,
    activityLevel: "Easy",
    soloFriendly: true,
    familyFriendly: false,
    departureMonths: [4, 5, 6, 9, 10],
    image: "tibet",
    gallery: ["tibet", "tripTibet"],
    strategicPriority: 82,
    customizable: true,
    tags: ["Lhasa", "Potala Palace", "Jokhang Temple", "Barkhor", "Short Tibet Trip"],
    searchAliases: ["lhasa", "tibet", "potala", "jokhang", "barkhor", "short tibet"],
    highlights: ["The Potala Palace", "Jokhang Temple and the Barkhor kora", "A short, well-paced altitude introduction", "Private guide throughout"],
    whoFor: ["Travelers short on time who still want Tibet", "Those testing how they handle altitude", "Add-on to a wider China trip"],
    itinerary: [
      { day: 1, title: "Arrive Lhasa — rest", summary: "Rest and acclimatize to 3,600m.", highlights: ["Rest"], meals: "Dinner", accommodation: "Lhasa hotel" },
      { day: 2, title: "Potala & Jokhang", summary: "Lhasa's two greatest landmarks and the Barkhor.", highlights: ["Potala Palace", "Jokhang"], meals: "Breakfast", accommodation: "Lhasa hotel" },
      { day: 3, title: "Sera & old town", summary: "Sera Monastery debates and old Lhasa lanes.", highlights: ["Sera debates"], meals: "Breakfast", accommodation: "Lhasa hotel" },
      { day: 4, title: "Departure", summary: "Transfer for onward travel.", highlights: ["Transfer"], meals: "Breakfast" },
    ],
    included: ["3 nights accommodation", "Tibet Travel Permit coordination", "Licensed guide", "Private vehicle", "Site tickets", "Daily breakfast"],
    notIncluded: ["Flights or rail to Lhasa", "China visa", "Travel insurance (required)", "Most meals", "Tips"],
    accommodation: "A comfortable boutique hotel in central Lhasa.",
    transport: "Private vehicle and licensed guide within Lhasa.",
    cancellation: "Free cancellation up to 45 days before departure due to permit lead times.",
    hostSlug: "tashi",
    departures: [
      { date: "2026-05-10", status: "available", priceUSD: 980 },
      { date: "2026-06-07", status: "available", priceUSD: 1010 },
      { date: "2026-09-06", status: "available", priceUSD: 1030 },
    ],
    faqs: [
      { question: "Is four days enough for Tibet?", answer: "It's a focused first taste centered on Lhasa, with time to adjust to altitude. For lakes and Shigatse, consider Tibet Essentials instead." },
      { question: "Do I still need a permit for a short stay?", answer: "Yes — any trip to Tibet needs a Tibet Travel Permit and a licensed guide. We coordinate the documentation after eligibility is confirmed." },
    ],
  },
  {
    slug: "tibet-dream-tour-10-day",
    name: "10-Day Tibet Dream Tour: Lhasa & East Tibet",
    category: "Mountains & Nature",
    style: "Small Group",
    tagline: "The green side of the plateau — Lhasa's landmarks, the forests, glaciers and alpine lakes of Nyingchi and Bomi, and the holy lakes of Yamdrok and Namtso.",
    durationValue: 10,
    durationUnit: "days",
    route: ["Lhasa", "Nyingchi", "Bomi", "Ranwu Lake", "Basum Tso", "Yamdrok Lake", "Namtso"],
    destinationSlugs: ["tibet"],
    travelStyleSlugs: ["mountains-nature", "ancient-culture", "slow-local", "small-group"],
    fromPriceUSD: 2450,
    rating: 0,
    reviewCount: 0,
    isNew: true,
    maxGroupSize: 12,
    activityLevel: "Moderate",
    soloFriendly: true,
    familyFriendly: false,
    departureMonths: [4, 5, 6, 7, 8, 9, 10],
    image: "tripTibet",
    gallery: ["tripTibet", "spotlightTibet", "tibet"],
    featured: true,
    strategicPriority: 91,
    customizable: true,
    tags: ["Tibet", "Nyingchi", "Bomi", "Basum Tso", "Ranwu Lake", "Midui Glacier", "Namtso", "Yamdrok", "East Tibet", "Forest"],
    searchAliases: ["tibet", "nyingchi", "linzhi", "bomi", "ranwu", "rawok", "basum", "basum tso", "draksum", "midui", "midui glacier", "namtso", "yamdrok", "lhasa", "east tibet", "dream tour"],
    highlights: [
      "'Tibet's Switzerland' — the forests and alpine scenery of Nyingchi and Bomi",
      "The Midui Glacier and mirror-like Ranwu Lake in east Tibet",
      "Basum Tso, a sacred island lake and national AAAAA park",
      "Two holy lakes — Yamdrok and Namtso — plus Lhasa's Potala and Jokhang",
    ],
    whoFor: ["Travelers wanting Tibet's greener, lower-altitude east", "Nature and photography lovers", "Those who prefer scenery and light walking to hard climbs"],
    itinerary: [
      { day: 1, title: "Arrive in Lhasa", summary: "Arrive in Lhasa, met with a khata welcome, and rest to adjust to 3,650m.", highlights: ["Pickup", "Rest & acclimatize"], accommodation: "4-star oxygen-equipped hotel, Lhasa" },
      { day: 2, title: "Potala Palace, Jokhang & Barkhor", summary: "The Potala Palace, the Jokhang Temple and a City Walk on the Barkhor pilgrim circuit.", highlights: ["Potala Palace", "Jokhang Temple", "Barkhor kora"], meals: "Breakfast, dinner", accommodation: "4-star oxygen-equipped hotel, Lhasa" },
      { day: 3, title: "Ganden Monastery to Nyingchi", summary: "Ganden Monastery (one of the three great Gelugpa temples), then the Lalin expressway through the Mila Tunnel to Nyingchi, following the Niyang River.", highlights: ["Ganden Monastery", "Mila Tunnel", "Niyang River"], meals: "Breakfast", accommodation: "4-star hotel, Nyingchi" },
      { day: 4, title: "Lulang Forest to Bomi", summary: "Over the Sejila Pass (Namcha Barwa viewpoint), through the Lulang alpine forest and pastures, and on to Galang Lake and Bomi.", highlights: ["Sejila Pass", "Lulang Forest", "Galang Lake"], meals: "Breakfast", accommodation: "4-star hotel, Bomi" },
      { day: 5, title: "Midui Glacier & Ranwu Lake", summary: "The Midui Glacier — one of China's lowest-altitude glaciers — and a loop of Ranwu Lake, the largest lake in east Tibet, returning to Bomi.", highlights: ["Midui Glacier", "Ranwu Lake"], meals: "Breakfast", accommodation: "4-star hotel, Bomi" },
      { day: 6, title: "Guxiang Lake & a forest walk", summary: "Guxiang Lake, then a light hike through the Gang Spruce Forest — one of 'China's ten most beautiful forests' — before returning to Nyingchi.", highlights: ["Guxiang Lake", "Gang Spruce Forest hike"], meals: "Breakfast", accommodation: "4-star hotel, Nyingchi" },
      { day: 7, title: "Basum Tso to Lhasa", summary: "Basum Tso and its central island — a national AAAAA park known as 'Little Switzerland' — then back to Lhasa for an intangible-heritage handicraft experience.", highlights: ["Basum Tso", "Handicraft experience"], meals: "Breakfast", accommodation: "4-star oxygen-equipped hotel, Lhasa" },
      { day: 8, title: "Yamdrok Lake & Karula Glacier", summary: "Over the Gangbala Pass to turquoise Yamdrok Lake and the Karula Glacier, then the evening 'Princess Wencheng' live drama.", highlights: ["Yamdrok Lake", "Karula Glacier", "Princess Wencheng show"], meals: "Breakfast", accommodation: "4-star oxygen-equipped hotel, Lhasa" },
      { day: 9, title: "Namtso Lake", summary: "Along the Nyenchen Tanglha range to Namtso (4,718m), returning via the 5,190m Laganla Pass with a high-altitude challenge certificate.", highlights: ["Nyenchen Tanglha", "Namtso Lake", "Laganla Pass"], meals: "Breakfast, dinner", accommodation: "4-star oxygen-equipped hotel, Lhasa" },
      { day: 10, title: "Departure", summary: "Transfer to the railway station or airport for your onward journey.", highlights: ["Transfer"], meals: "Breakfast" },
    ],
    included: [
      "9 nights 4-star hotels (oxygen-equipped in Lhasa)",
      "9 breakfasts and 2 dinners (meals alcohol-free)",
      "Bilingual Chinese/English guide throughout",
      "First-entry tickets to all listed sights (incl. Princess Wencheng show)",
      "Private 7–29 seat vehicle for a 2–12 person MINI group",
      "Tibet Travel Permit coordination and foreign-guest registration in Nyingchi",
      "Zero forced shopping, zero self-pay stops",
    ],
    notIncluded: [
      "Rail or flight to/from Lhasa",
      "China visa",
      "Travel insurance (recommended)",
      "Single-room supplement",
      "Meals not listed, and children's tickets",
      "Personal expenses and anything from force-majeure delays",
    ],
    accommodation: "Nine nights in 4-star hotels across Lhasa (oxygen-equipped), Nyingchi and Bomi, chosen for comfort within each town's options.",
    transport: "A private 7–29 seat vehicle for a small MINI group of 2–12 travelers with a bilingual guide, mostly along the scenic G318. Rail or flight to Lhasa is arranged separately.",
    cancellation: "A minimum of 2 travelers is required to operate; if not met we may cancel up to 7 days before departure and refund in full. Voluntarily skipping included transport, hotels or sights is non-refundable.",
    hostSlug: "tashi",
    departures: [
      { date: "2026-05-12", status: "available", priceUSD: 2450 },
      { date: "2026-06-16", status: "available", priceUSD: 2510 },
      { date: "2026-08-18", status: "available", priceUSD: 2550 },
      { date: "2026-09-15", status: "limited", priceUSD: 2550 },
    ],
    faqs: [
      { question: "How does east Tibet compare to the Everest route?", answer: "Nyingchi and Bomi are lower, greener and gentler — forests, glaciers and alpine lakes rather than high desert. It's the easier-altitude side of Tibet, with only light walking, while still including Lhasa, Yamdrok and Namtso." },
      { question: "Do I still need a Tibet permit?", answer: "Yes — any trip into the Tibet Autonomous Region needs a Tibet Travel Permit and a licensed guide, and Nyingchi requires a foreign-guest registration on arrival. We coordinate both after booking eligibility is confirmed. A permit is not a visa." },
    ],
  },
  {
    slug: "chengdu-and-tibet-discovery",
    name: "Chengdu & Tibet Discovery",
    category: "First Time in China",
    style: "Private",
    tagline: "Our flagship cross-region journey — Chengdu's pandas and food, then the palaces, lakes and monasteries of the Tibetan plateau.",
    durationValue: 11,
    durationUnit: "days",
    route: ["Chengdu", "Lhasa", "Yamdrok Lake", "Shigatse"],
    destinationSlugs: ["chengdu", "tibet"],
    travelStyleSlugs: ["first-time", "food-nightlife", "mountains-nature", "private"],
    fromPriceUSD: 2980,
    rating: 0,
    reviewCount: 0,
    isNew: true,
    maxGroupSize: 8,
    activityLevel: "Moderate",
    soloFriendly: true,
    familyFriendly: false,
    departureMonths: [4, 5, 6, 9, 10],
    image: "tripChengdu",
    gallery: ["tripChengdu", "tripTibet", "spotlightTibet"],
    featured: true,
    strategicPriority: 99,
    customizable: true,
    tags: ["Chengdu", "Tibet", "Pandas", "Lhasa", "Food", "Culture", "Flagship", "Cross-region"],
    searchAliases: ["chengdu", "tibet", "panda", "lhasa", "sichuan", "food", "flagship", "discovery"],
    highlights: [
      "Chengdu's pandas, tea houses and Sichuan food",
      "The palaces and monasteries of Lhasa",
      "Sacred Yamdrok Lake and Shigatse",
      "Our two core regions in one flagship journey",
    ],
    whoFor: ["First-timers who want food, culture and the plateau", "Travelers combining our two core regions", "Those wanting a single, fully-handled itinerary"],
    itinerary: [
      { day: 1, title: "Arrive Chengdu", summary: "Easy evening welcome walk.", highlights: ["Jinli street"], meals: "Dinner", accommodation: "Chengdu hotel" },
      { day: 2, title: "Pandas & tea houses", summary: "Panda base at dawn, slow afternoon.", highlights: ["Giant panda base"], meals: "Breakfast", accommodation: "Chengdu hotel" },
      { day: 3, title: "Chengdu food day", summary: "Market, cooking and a hotpot night.", highlights: ["Sichuan cooking", "Hotpot"], meals: "Breakfast, lunch", accommodation: "Chengdu hotel" },
      { day: 4, title: "Fly to Lhasa — rest", summary: "Short flight to the plateau; rest on arrival.", highlights: ["Rest"], meals: "Breakfast", accommodation: "Lhasa hotel" },
      { day: 5, title: "Potala & Jokhang", summary: "Lhasa's great landmarks and the Barkhor.", highlights: ["Potala Palace", "Jokhang"], meals: "Breakfast", accommodation: "Lhasa hotel" },
      { day: 6, title: "Lhasa monasteries", summary: "Sera and Drepung.", highlights: ["Sera debates"], meals: "Breakfast", accommodation: "Lhasa hotel" },
      { day: 7, title: "Yamdrok Lake", summary: "Kamba La pass to the sacred lake.", highlights: ["Yamdrok Lake"], meals: "Breakfast", accommodation: "Lhasa hotel" },
      { day: 8, title: "To Shigatse", summary: "Gyantse Kumbum en route.", highlights: ["Gyantse Kumbum"], meals: "Breakfast", accommodation: "Shigatse hotel" },
      { day: 9, title: "Tashilhunpo & return", summary: "Shigatse's monastery, back toward Lhasa.", highlights: ["Tashilhunpo"], meals: "Breakfast", accommodation: "Lhasa hotel" },
      { day: 10, title: "Lhasa free time", summary: "A gentle final plateau day.", highlights: ["Old town"], meals: "Breakfast", accommodation: "Lhasa hotel" },
      { day: 11, title: "Departure", summary: "Transfer for onward travel.", highlights: ["Transfer"], meals: "Breakfast" },
    ],
    included: ["Chengdu + Tibet accommodation", "Chengdu–Lhasa flight", "Tibet permits coordination", "Licensed Tibetan guide", "Chengdu host", "Private vehicles", "Daily breakfast and selected meals"],
    notIncluded: ["International flights", "China visa", "Travel insurance (required)", "Most meals", "Tips"],
    accommodation: "Boutique hotels in Chengdu, Lhasa and Shigatse.",
    transport: "Flight from Chengdu to Lhasa; private vehicles throughout.",
    cancellation: "Free cancellation up to 45 days before departure due to permit lead times.",
    hostSlug: "tashi",
    departures: [
      { date: "2026-05-20", status: "available", priceUSD: 2980 },
      { date: "2026-06-17", status: "available", priceUSD: 3060 },
      { date: "2026-09-16", status: "limited", priceUSD: 3100 },
    ],
    faqs: [
      { question: "Why is this the flagship trip?", answer: "It connects our two founding core regions — Chengdu and Tibet — into one seamless journey: food and pandas first, then the plateau, with every detail handled." },
      { question: "Do we fly or take the train to Tibet?", answer: "This itinerary flies Chengdu–Lhasa to save time. If you'd prefer the scenic railway, see Chengdu to Tibet by Train, or ask us to customize." },
    ],
  },

  // ==========================================================================
  // Additional Chengdu inventory — strategic core destination.
  // ==========================================================================
  {
    slug: "chengdu-panda-tea-house-day",
    name: "Chengdu Panda & Tea House Day",
    category: "City Experience",
    style: "Private",
    tagline: "A private full day pairing dawn at the panda base with the slow ritual of a Chengdu tea house.",
    durationValue: 1,
    durationUnit: "days",
    route: ["Chengdu"],
    destinationSlugs: ["chengdu"],
    travelStyleSlugs: ["city-experience", "slow-local", "private"],
    fromPriceUSD: 180,
    rating: 0,
    reviewCount: 0,
    isNew: true,
    maxGroupSize: 6,
    activityLevel: "Easy",
    soloFriendly: true,
    familyFriendly: true,
    departureMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    image: "tripChengdu",
    gallery: ["tripChengdu", "chengdu", "reviewPanda"],
    strategicPriority: 74,
    customizable: true,
    tags: ["Chengdu", "Panda", "Pandas", "Tea House", "Sichuan", "Day Trip"],
    searchAliases: ["chengdu", "panda", "pandas", "tea house", "teahouse", "sichuan", "day trip"],
    highlights: ["The panda base at opening, when pandas are most active", "A classic Chengdu tea-house afternoon", "A private guide and driver for the day"],
    whoFor: ["Families and first-timers", "Travelers with one full day in Chengdu", "Panda lovers"],
    itinerary: [
      { day: 1, title: "Pandas at dawn, tea by afternoon", summary: "Early panda base, then a relaxed tea house and old-town stroll.", highlights: ["Giant panda base", "Tea house"], meals: "None" },
    ],
    included: ["Private guide and driver (full day)", "Panda base tickets", "Tea-house visit"],
    notIncluded: ["Accommodation", "Flights", "China visa", "Meals", "Tips"],
    accommodation: "Not applicable — a day experience.",
    transport: "Private vehicle with driver for the day.",
    cancellation: "Free cancellation up to 24 hours before the experience.",
    hostSlug: "lina",
    departures: [
      { date: "2026-06-29", status: "available", priceUSD: 180 },
      { date: "2026-07-06", status: "available", priceUSD: 180 },
    ],
    faqs: [
      { question: "When do we see the pandas?", answer: "Right at opening — pandas are most active in the cool morning and the base fills up later." },
    ],
  },
  {
    slug: "chengdu-food-weekend",
    name: "Chengdu Food Weekend",
    category: "Food & Nightlife",
    style: "Small Group",
    tagline: "Two days eating your way through Chengdu — markets, hotpot, street snacks and the city after dark.",
    durationValue: 2,
    durationUnit: "days",
    route: ["Chengdu"],
    destinationSlugs: ["chengdu"],
    travelStyleSlugs: ["food-nightlife", "small-group", "city-experience"],
    fromPriceUSD: 320,
    rating: 0,
    reviewCount: 0,
    isNew: true,
    maxGroupSize: 8,
    activityLevel: "Easy",
    soloFriendly: true,
    familyFriendly: false,
    departureMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    image: "tripChengduNight",
    gallery: ["tripChengduNight", "chengdu"],
    strategicPriority: 70,
    customizable: true,
    tags: ["Chengdu", "Food", "Hotpot", "Street Food", "Sichuan", "Nightlife", "Mala"],
    searchAliases: ["chengdu", "food", "hotpot", "mala", "street food", "sichuan", "nightlife"],
    highlights: ["A market-to-table Sichuan cooking session", "A guided hotpot night", "Street-snack crawls and a night market"],
    whoFor: ["Food-led travelers", "Weekend city-breakers", "Anyone who wants to eat like a local"],
    itinerary: [
      { day: 1, title: "Markets & cooking", summary: "A market visit and hands-on Sichuan cooking, then snacks.", highlights: ["Cooking class", "Snack crawl"], meals: "Breakfast, lunch", accommodation: "Central hotel" },
      { day: 2, title: "Hotpot & night market", summary: "A relaxed day and a guided hotpot and night-market evening.", highlights: ["Hotpot night", "Night market"], meals: "Breakfast", accommodation: "Central hotel" },
    ],
    included: ["1 night central accommodation", "Local food host", "Cooking class", "Hotpot dinner", "Daily breakfast"],
    notIncluded: ["Flights or rail to Chengdu", "China visa", "Some meals", "Tips"],
    accommodation: "A central boutique hotel near the snack streets.",
    transport: "Walkable and metro-friendly; short taxi hops covered.",
    cancellation: "Free cancellation up to 7 days before departure.",
    hostSlug: "lina",
    departures: [
      { date: "2026-06-28", status: "available", priceUSD: 320 },
      { date: "2026-07-12", status: "available", priceUSD: 320 },
    ],
    faqs: [
      { question: "How spicy is it?", answer: "Sichuan food is bold, but your host adjusts every stop and always offers milder options." },
    ],
  },
  {
    slug: "chengdu-and-western-sichuan",
    name: "Chengdu & Western Sichuan",
    category: "Mountains & Nature",
    style: "Small Group",
    tagline: "From Chengdu's tea houses into the high grasslands and monastery towns of western Sichuan.",
    durationValue: 7,
    durationUnit: "days",
    route: ["Chengdu", "Kangding", "Tagong", "Danba"],
    destinationSlugs: ["chengdu"],
    travelStyleSlugs: ["mountains-nature", "slow-local", "small-group"],
    fromPriceUSD: 1480,
    rating: 0,
    reviewCount: 0,
    isNew: true,
    maxGroupSize: 10,
    activityLevel: "Active",
    soloFriendly: true,
    familyFriendly: false,
    departureMonths: [5, 6, 7, 8, 9, 10],
    image: "chengdu",
    gallery: ["chengdu", "tripChengdu", "yunnan"],
    strategicPriority: 72,
    customizable: true,
    tags: ["Chengdu", "Western Sichuan", "Kangding", "Tagong", "Grasslands", "Kham"],
    searchAliases: ["chengdu", "sichuan", "western sichuan", "kangding", "tagong", "danba", "grasslands", "kham"],
    highlights: ["Tagong's grasslands and monastery", "The watchtowers and villages of Danba", "A gentle taste of Tibetan culture without leaving Sichuan"],
    whoFor: ["Active travelers wanting mountains near Chengdu", "Those curious about Tibetan-edge culture", "Photographers"],
    itinerary: [
      { day: 1, title: "Chengdu", summary: "Arrive and settle in.", highlights: ["Welcome dinner"], meals: "Dinner", accommodation: "Chengdu hotel" },
      { day: 2, title: "To Kangding", summary: "Drive west into the mountains.", highlights: ["Mountain roads"], meals: "Breakfast", accommodation: "Kangding hotel" },
      { day: 3, title: "Tagong grasslands", summary: "Grasslands, a monastery and big skies.", highlights: ["Tagong Monastery", "Grasslands"], meals: "Breakfast", accommodation: "Tagong guesthouse" },
      { day: 4, title: "Tagong to Danba", summary: "Scenic drive to the watchtower valleys.", highlights: ["Scenic drive"], meals: "Breakfast", accommodation: "Danba guesthouse" },
      { day: 5, title: "Danba villages", summary: "Ancient stone watchtowers and villages.", highlights: ["Watchtowers", "Villages"], meals: "Breakfast", accommodation: "Danba guesthouse" },
      { day: 6, title: "Return toward Chengdu", summary: "Descend back toward the city.", highlights: ["Scenic drive"], meals: "Breakfast", accommodation: "Chengdu hotel" },
      { day: 7, title: "Departure", summary: "Transfer for onward travel.", highlights: ["Transfer"], meals: "Breakfast" },
    ],
    included: ["6 nights accommodation", "English-speaking guide", "Private vehicle", "Listed activities", "Daily breakfast and selected meals"],
    notIncluded: ["Flights or rail to Chengdu", "China visa", "Travel insurance", "Some meals", "Tips"],
    accommodation: "City hotels and characterful guesthouses in the mountains.",
    transport: "Private vehicle on mountain roads.",
    cancellation: "Free cancellation up to 30 days before departure.",
    hostSlug: "mia",
    departures: [
      { date: "2026-06-06", status: "available", priceUSD: 1480 },
      { date: "2026-07-11", status: "available", priceUSD: 1520 },
      { date: "2026-09-05", status: "limited", priceUSD: 1540 },
    ],
    faqs: [
      { question: "Do I need a Tibet permit for western Sichuan?", answer: "No — western Sichuan is outside the Tibet Autonomous Region, so no Tibet Travel Permit is required, while still offering Tibetan-edge culture and scenery." },
    ],
  },
];

export function getAllTrips(): Trip[] {
  return trips;
}

export function getTripBySlug(slug: string): Trip | undefined {
  return trips.find((t) => t.slug === slug);
}

export function getBestSellerTrips(): Trip[] {
  return trips.filter((t) => t.bestSeller);
}

export function getTripsByDestination(slug: string): Trip[] {
  return trips.filter((t) => t.destinationSlugs.includes(slug));
}

export function getTripsByTravelStyle(slug: string): Trip[] {
  return trips.filter((t) => t.travelStyleSlugs.includes(slug));
}

export function getRelatedTrips(trip: Trip, limit = 3): Trip[] {
  return trips
    .filter((t) => t.slug !== trip.slug)
    .map((t) => ({
      t,
      score:
        t.destinationSlugs.filter((d) => trip.destinationSlugs.includes(d)).length * 2 +
        t.travelStyleSlugs.filter((s) => trip.travelStyleSlugs.includes(s)).length,
    }))
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((x) => x.t);
}
