import type { Trip } from "./types";

/**
 * Mock trip catalog. Realistic sample data for prototyping only — prices,
 * dates, ratings and review counts must be replaced with verified data before
 * launch. Departure dates use 2026 to match the planning window.
 */
export const trips: Trip[] = [
  {
    slug: "china-essentials",
    name: "China Essentials",
    category: "First Time in China",
    style: "Small Group",
    tagline: "The three icons — Beijing, Xi'an and Shanghai — done properly, without the tourist-trap autopilot.",
    durationValue: 8,
    durationUnit: "days",
    route: ["Beijing", "Xi'an", "Shanghai"],
    destinationSlugs: ["beijing", "xian", "shanghai"],
    travelStyleSlugs: ["first-time", "small-group"],
    fromPriceUSD: 1680,
    rating: 4.9,
    reviewCount: 214,
    maxGroupSize: 12,
    activityLevel: "Moderate",
    soloFriendly: true,
    familyFriendly: true,
    departureMonths: [3, 4, 5, 9, 10, 11],
    image: "tripEssentials",
    gallery: ["tripEssentials", "beijing", "xian", "shanghai"],
    bestSeller: true,
    customizable: true,
    highlights: [
      "A quiet-hours visit to the Great Wall at a restored-but-uncrowded section",
      "The Terracotta Warriors with a local archaeologist as your guide",
      "A hutong breakfast crawl most tour groups never see",
      "High-speed rail between every city — no internal flights, no airport queues",
    ],
    whoFor: [
      "First-time visitors who want the icons without a rushed coach-tour feel",
      "Travelers who care about food and street-level culture",
      "Solo travelers and couples comfortable in a small group",
    ],
    itinerary: [
      { day: 1, title: "Arrive in Beijing", summary: "Airport pickup, hotel check-in and an evening orientation walk with your guide.", highlights: ["Meet your group", "Evening dumpling dinner"], meals: "Dinner", accommodation: "Boutique courtyard hotel" },
      { day: 2, title: "Great Wall, quiet section", summary: "A full day at a restored-but-peaceful stretch of the Wall, away from the crowds.", highlights: ["Cable car up, walk down", "Picnic lunch on the ramparts"], meals: "Breakfast, lunch", accommodation: "Boutique courtyard hotel" },
      { day: 3, title: "Forbidden City & hutongs", summary: "The imperial core in the morning, then a walking food crawl through the old lanes.", highlights: ["Forbidden City", "Hutong breakfast crawl"], meals: "Breakfast", accommodation: "Boutique courtyard hotel" },
      { day: 4, title: "High-speed rail to Xi'an", summary: "Glide south by bullet train, then an evening on the city wall.", highlights: ["High-speed rail", "City wall at sunset"], meals: "Breakfast", accommodation: "Design hotel near the Bell Tower" },
      { day: 5, title: "Terracotta Warriors", summary: "A morning with the warriors guided by a local archaeologist, then the Muslim Quarter for lunch.", highlights: ["Terracotta Army", "Muslim Quarter street food"], meals: "Breakfast, lunch", accommodation: "Design hotel near the Bell Tower" },
      { day: 6, title: "High-speed rail to Shanghai", summary: "Travel east and arrive into China's most future-facing city.", highlights: ["High-speed rail", "Bund evening walk"], meals: "Breakfast", accommodation: "Riverside design hotel" },
      { day: 7, title: "Shanghai, old and new", summary: "The former French Concession by day, rooftop skyline by night.", highlights: ["French Concession", "Rooftop drinks"], meals: "Breakfast", accommodation: "Riverside design hotel" },
      { day: 8, title: "Departure", summary: "Free morning and airport transfer whenever your flight leaves.", highlights: ["Free time", "Airport transfer"], meals: "Breakfast" },
    ],
    included: [
      "7 nights boutique accommodation",
      "All high-speed rail between cities",
      "English-speaking local guides in each city",
      "Daily breakfast and selected meals",
      "All listed entrance tickets",
      "Airport transfers",
    ],
    notIncluded: ["International flights", "China visa or transit permit", "Travel insurance", "Most lunches and dinners", "Personal expenses and tips"],
    accommodation: "Hand-picked boutique and design hotels rated 4 stars or above, chosen for location and character over chain uniformity.",
    transport: "City-to-city travel is entirely by high-speed rail in second class (first-class upgrade available). Private vehicles for day excursions.",
    cancellation: "Free cancellation up to 30 days before departure. 50% refund up to 14 days before. See full booking conditions for details.",
    hostSlug: "eric",
    departures: [
      { date: "2026-03-21", status: "available", priceUSD: 1680 },
      { date: "2026-04-18", status: "limited", priceUSD: 1740 },
      { date: "2026-05-16", status: "guaranteed", priceUSD: 1740 },
      { date: "2026-09-19", status: "available", priceUSD: 1760 },
      { date: "2026-10-17", status: "limited", priceUSD: 1820 },
    ],
    faqs: [
      { question: "Do I need a visa for this trip?", answer: "Most travelers need a tourist (L) visa or may qualify for a visa-free transit policy depending on nationality and routing. We send a personalized checklist after booking, but always confirm current rules with your nearest Chinese embassy." },
      { question: "How big is the group?", answer: "Maximum 12 travelers. The average group is 8–10, with a single local guide per city." },
      { question: "Is this trip good for solo travelers?", answer: "Yes — roughly a third of travelers join solo. A single supplement applies for a private room, or we can pair same-gender roommates on request." },
    ],
  },
  {
    slug: "chengdu-after-dark",
    name: "Chengdu After Dark",
    category: "Food & Nightlife",
    style: "Food & Nightlife",
    tagline: "A four-hour evening crawl through Chengdu's night markets, hotpot dens and tea-house backstreets with a local food host.",
    durationValue: 4,
    durationUnit: "hours",
    route: ["Chengdu"],
    destinationSlugs: ["chengdu"],
    travelStyleSlugs: ["food-nightlife", "city-experience"],
    fromPriceUSD: 68,
    rating: 4.95,
    reviewCount: 389,
    maxGroupSize: 8,
    activityLevel: "Easy",
    soloFriendly: true,
    familyFriendly: true,
    departureMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    image: "tripChengduNight",
    gallery: ["tripChengduNight", "chengdu", "reviewMarket"],
    bestSeller: true,
    customizable: false,
    highlights: [
      "Six to eight tastings across markets, stalls and a family hotpot spot",
      "A spice-level walkthrough so you order like a local, not a tourist",
      "A late tea house where locals play mahjong past midnight",
    ],
    whoFor: ["Food-led travelers", "Evening arrivals with one night in Chengdu", "Anyone nervous about ordering Sichuan food solo"],
    itinerary: [
      { day: 1, title: "Meet at the night market", summary: "Gather at dusk and start with skewers and a cold-noodle warm-up.", highlights: ["Street skewers", "Spice-level briefing"] },
      { day: 2, title: "Hotpot with a local family", summary: "Sit down for the main event — mala broth, the dipping-sauce ritual and plenty of stories.", highlights: ["Family hotpot", "Sauce bar masterclass"] },
      { day: 3, title: "Tea house & mahjong lanes", summary: "Wind down in a backstreet tea house where the night is just getting going.", highlights: ["Late tea house", "Mahjong watching"] },
    ],
    included: ["Local food host for 4 hours", "All food tastings (6–8 stops)", "One round of tea or a local drink", "Spice-level guidance"],
    notIncluded: ["Hotel pickup", "Additional alcoholic drinks", "Gratuities"],
    accommodation: "Not applicable — this is an evening experience.",
    transport: "On foot, with one short metro or taxi hop covered by your host.",
    cancellation: "Free cancellation up to 24 hours before the experience.",
    hostSlug: "lina",
    departures: [
      { date: "2026-06-30", status: "available", priceUSD: 68 },
      { date: "2026-07-01", status: "available", priceUSD: 68 },
      { date: "2026-07-02", status: "limited", priceUSD: 68 },
    ],
    faqs: [
      { question: "How spicy is the food?", answer: "Sichuan food is famously bold, but your host adjusts every stop and always offers milder options. Tell us your limit and we'll order around it." },
      { question: "Can you cater to dietary needs?", answer: "Vegetarian routing is possible with advance notice. Strict vegan and some allergy needs are harder with hotpot — message us first and we'll be honest about what works." },
    ],
  },
  {
    slug: "wild-yunnan",
    name: "Wild Yunnan",
    category: "Mountains & Nature",
    style: "Small Group",
    tagline: "From Kunming's lakes to Shangri-La's high meadows — old towns, tea hills and Himalayan foothills at an unhurried pace.",
    durationValue: 9,
    durationUnit: "days",
    route: ["Kunming", "Dali", "Shaxi", "Shangri-La"],
    destinationSlugs: ["yunnan"],
    travelStyleSlugs: ["mountains-nature", "small-group", "slow-local"],
    fromPriceUSD: 2150,
    rating: 4.9,
    reviewCount: 156,
    maxGroupSize: 10,
    activityLevel: "Active",
    soloFriendly: true,
    familyFriendly: false,
    departureMonths: [3, 4, 5, 6, 9, 10],
    image: "tripWildYunnan",
    gallery: ["tripWildYunnan", "yunnan"],
    bestSeller: false,
    customizable: true,
    highlights: [
      "A walking morning around Dali's old town and Erhai Lake",
      "An overnight in tiny Shaxi, a restored caravan town on the old Tea Horse Road",
      "Tibetan-Yunnan monasteries and meadows around Shangri-La",
    ],
    whoFor: ["Active travelers who like walking and altitude", "Photographers and slow-travel fans", "Travelers wanting a non-obvious second China trip"],
    itinerary: [
      { day: 1, title: "Arrive Kunming", summary: "Land in the 'spring city' and settle in.", highlights: ["Welcome dinner"], meals: "Dinner", accommodation: "Garden hotel" },
      { day: 2, title: "Kunming to Dali", summary: "Travel west to lakeside Dali and its old town walls.", highlights: ["High-speed rail", "Old town walk"], meals: "Breakfast", accommodation: "Courtyard inn" },
      { day: 3, title: "Erhai Lake & villages", summary: "Cycle and walk the lakeshore, stopping in Bai villages.", highlights: ["Lakeside cycling", "Bai village lunch"], meals: "Breakfast, lunch", accommodation: "Courtyard inn" },
      { day: 4, title: "Into Shaxi", summary: "Drive the back roads to the restored caravan town of Shaxi.", highlights: ["Tea Horse Road", "Sideng market square"], meals: "Breakfast", accommodation: "Heritage inn" },
      { day: 5, title: "Shaxi valley walk", summary: "A gentle valley hike between hamlets and terraced fields.", highlights: ["Valley hike", "Local farmhouse lunch"], meals: "Breakfast, lunch", accommodation: "Heritage inn" },
      { day: 6, title: "Climb to Shangri-La", summary: "Ascend onto the plateau; take it slow as the altitude rises.", highlights: ["Scenic drive", "Old town evening"], meals: "Breakfast", accommodation: "Tibetan-style lodge" },
      { day: 7, title: "Monasteries & meadows", summary: "Visit Songzanlin Monastery and walk the high meadows.", highlights: ["Songzanlin Monastery", "Meadow walk"], meals: "Breakfast, lunch", accommodation: "Tibetan-style lodge" },
      { day: 8, title: "Plateau free day", summary: "Optional day hike or a slow day with tea and views.", highlights: ["Optional hike", "Free time"], meals: "Breakfast", accommodation: "Tibetan-style lodge" },
      { day: 9, title: "Departure", summary: "Transfer to Shangri-La airport for onward flights.", highlights: ["Airport transfer"], meals: "Breakfast" },
    ],
    included: ["8 nights characterful accommodation", "Internal high-speed rail and private drives", "English-speaking guide throughout", "Daily breakfast and selected meals", "All listed activities and entrance fees"],
    notIncluded: ["Flights to/from Yunnan", "China visa", "Travel insurance", "Some meals", "Tips"],
    accommodation: "Locally owned courtyard inns, a heritage property in Shaxi and a Tibetan-style lodge in Shangri-La.",
    transport: "A mix of high-speed rail, private vehicle on mountain roads, and walking days. One short domestic flight out.",
    cancellation: "Free cancellation up to 45 days before departure given the remote logistics. See booking conditions.",
    hostSlug: "mia",
    departures: [
      { date: "2026-04-11", status: "available", priceUSD: 2150 },
      { date: "2026-05-09", status: "limited", priceUSD: 2210 },
      { date: "2026-09-12", status: "available", priceUSD: 2250 },
      { date: "2026-10-10", status: "limited", priceUSD: 2310 },
    ],
    faqs: [
      { question: "How high do we go?", answer: "Shangri-La sits at around 3,200m. We build in time to acclimatize and keep the first day there gentle, but talk to your doctor if you have heart or lung conditions." },
      { question: "Is this trip suitable for children?", answer: "Because of the altitude and the number of walking days, we recommend this trip for ages 14 and up." },
    ],
  },
  {
    slug: "beijing-stopover",
    name: "Beijing Stopover",
    category: "City Experience",
    style: "Private",
    tagline: "Two private days that turn a layover into a real Beijing — Wall, hutongs and roast duck, on your schedule.",
    durationValue: 2,
    durationUnit: "days",
    route: ["Beijing"],
    destinationSlugs: ["beijing"],
    travelStyleSlugs: ["city-experience", "private"],
    fromPriceUSD: 320,
    rating: 4.85,
    reviewCount: 97,
    maxGroupSize: 6,
    activityLevel: "Easy",
    soloFriendly: true,
    familyFriendly: true,
    departureMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    image: "tripBeijingStopover",
    gallery: ["tripBeijingStopover", "beijing"],
    bestSeller: false,
    customizable: true,
    highlights: ["A private guide and driver both days", "Great Wall in the morning before the crowds", "A roast-duck dinner picked by your guide"],
    whoFor: ["Travelers on a visa-free transit window", "Layovers of 48–72 hours", "Anyone who wants flexibility over a fixed group"],
    itinerary: [
      { day: 1, title: "Wall & old city", summary: "Early Great Wall visit, then the Forbidden City fringe and a hutong wander.", highlights: ["Great Wall", "Hutong walk"], meals: "Lunch", accommodation: "Your choice or we book" },
      { day: 2, title: "Temples & duck", summary: "Temple of Heaven, a tea house, and a roast-duck send-off dinner.", highlights: ["Temple of Heaven", "Roast duck dinner"], meals: "Breakfast" },
    ],
    included: ["Private English-speaking guide (2 days)", "Private vehicle and driver", "Listed entrance tickets", "One lunch and one dinner"],
    notIncluded: ["Accommodation (we can arrange)", "Flights", "Visa or transit permit", "Other meals", "Tips"],
    accommodation: "Not bundled by default — book your own or let us arrange a hotel near the airport express line.",
    transport: "Private vehicle with driver throughout, plus airport transfers on request.",
    cancellation: "Free cancellation up to 7 days before. Flexible re-timing for delayed connecting flights.",
    hostSlug: "eric",
    departures: [
      { date: "2026-06-29", status: "available", priceUSD: 320 },
      { date: "2026-07-03", status: "available", priceUSD: 320 },
      { date: "2026-07-10", status: "available", priceUSD: 320 },
    ],
    faqs: [
      { question: "Will I make my connecting flight?", answer: "We design the two days around your inbound and outbound times and keep buffers for traffic. Share your flight details and we'll plan backwards from departure." },
      { question: "Do I qualify for visa-free transit?", answer: "Many nationalities qualify for visa-free transit in Beijing when continuing to a third country within the allowed window. Rules change, so we confirm eligibility with you before booking." },
    ],
  },
  {
    slug: "china-by-high-speed-rail",
    name: "China by High-Speed Rail",
    category: "First Time in China",
    style: "Small Group",
    tagline: "Five cities, zero internal flights — a sweeping loop from Beijing to Shanghai threaded together by 300km/h trains.",
    durationValue: 12,
    durationUnit: "days",
    route: ["Beijing", "Xi'an", "Chengdu", "Guilin", "Shanghai"],
    destinationSlugs: ["beijing", "xian", "chengdu", "guilin", "shanghai"],
    travelStyleSlugs: ["first-time", "small-group"],
    fromPriceUSD: 2780,
    rating: 4.92,
    reviewCount: 131,
    maxGroupSize: 12,
    activityLevel: "Moderate",
    soloFriendly: true,
    familyFriendly: true,
    departureMonths: [3, 4, 5, 9, 10],
    image: "tripHighSpeed",
    gallery: ["tripHighSpeed", "beijing", "chengdu", "guilin"],
    bestSeller: true,
    customizable: true,
    highlights: ["The Great Wall, Warriors, pandas and karst rivers in one trip", "Every long leg by high-speed rail — see the country roll past", "A Li River cruise through the Guilin karst landscape"],
    whoFor: ["Travelers who want range without airport days", "Train lovers", "Second-timers wanting more than the big three"],
    itinerary: [
      { day: 1, title: "Arrive Beijing", summary: "Welcome and orientation.", highlights: ["Welcome dinner"], meals: "Dinner", accommodation: "Boutique hotel" },
      { day: 2, title: "Great Wall", summary: "A quiet Wall section.", highlights: ["Great Wall"], meals: "Breakfast, lunch", accommodation: "Boutique hotel" },
      { day: 3, title: "Imperial Beijing", summary: "Forbidden City and hutongs.", highlights: ["Forbidden City"], meals: "Breakfast", accommodation: "Boutique hotel" },
      { day: 4, title: "Rail to Xi'an", summary: "Bullet train south.", highlights: ["High-speed rail", "City wall"], meals: "Breakfast", accommodation: "Design hotel" },
      { day: 5, title: "Terracotta Warriors", summary: "Warriors and the Muslim Quarter.", highlights: ["Terracotta Army"], meals: "Breakfast, lunch", accommodation: "Design hotel" },
      { day: 6, title: "Rail to Chengdu", summary: "West to Sichuan.", highlights: ["High-speed rail"], meals: "Breakfast", accommodation: "City hotel" },
      { day: 7, title: "Pandas & tea houses", summary: "Morning at the panda base, afternoon tea-house life.", highlights: ["Panda base", "Tea house"], meals: "Breakfast", accommodation: "City hotel" },
      { day: 8, title: "Rail to Guilin", summary: "South to karst country.", highlights: ["High-speed rail"], meals: "Breakfast", accommodation: "Riverside hotel" },
      { day: 9, title: "Li River cruise", summary: "Cruise the river past the famous peaks.", highlights: ["Li River cruise"], meals: "Breakfast, lunch", accommodation: "Riverside hotel" },
      { day: 10, title: "Rail to Shanghai", summary: "East to the coast.", highlights: ["High-speed rail", "Bund walk"], meals: "Breakfast", accommodation: "Design hotel" },
      { day: 11, title: "Shanghai", summary: "Old and new Shanghai.", highlights: ["French Concession"], meals: "Breakfast", accommodation: "Design hotel" },
      { day: 12, title: "Departure", summary: "Airport transfer.", highlights: ["Airport transfer"], meals: "Breakfast" },
    ],
    included: ["11 nights accommodation", "All high-speed rail legs", "Li River cruise", "Local guides in each city", "Daily breakfast and selected meals", "Listed entrances and transfers"],
    notIncluded: ["International flights", "China visa", "Travel insurance", "Some meals", "Tips"],
    accommodation: "Boutique and design hotels across five cities, each chosen for location near the action.",
    transport: "Long legs by high-speed rail; private vehicles for excursions; one river cruise.",
    cancellation: "Free cancellation up to 30 days before departure. See booking conditions.",
    hostSlug: "eric",
    departures: [
      { date: "2026-03-28", status: "available", priceUSD: 2780 },
      { date: "2026-04-25", status: "limited", priceUSD: 2860 },
      { date: "2026-09-26", status: "available", priceUSD: 2920 },
      { date: "2026-10-17", status: "limited", priceUSD: 2980 },
    ],
    faqs: [
      { question: "Is 12 days too rushed for five cities?", answer: "Because every long leg is by high-speed rail you lose almost no time to airports. Each city gets at least a full day; the pace is moderate, not frantic." },
      { question: "Can I extend in any city?", answer: "Yes. This is a customizable departure — add nights in Chengdu or Shanghai and we'll adjust the rail tickets." },
    ],
  },
  {
    slug: "chongqing-city-rush",
    name: "Chongqing City Rush",
    category: "Big City Energy",
    style: "Private",
    tagline: "Three private days in the most vertical city on earth — cliffside neighborhoods, river light shows and the original mala hotpot.",
    durationValue: 3,
    durationUnit: "days",
    route: ["Chongqing"],
    destinationSlugs: ["chongqing"],
    travelStyleSlugs: ["big-city", "private", "food-nightlife"],
    fromPriceUSD: 540,
    rating: 4.8,
    reviewCount: 64,
    maxGroupSize: 6,
    activityLevel: "Moderate",
    soloFriendly: true,
    familyFriendly: true,
    departureMonths: [1, 2, 3, 4, 5, 9, 10, 11, 12],
    image: "tripChongqing",
    gallery: ["tripChongqing", "chongqing"],
    bestSeller: false,
    customizable: true,
    highlights: ["Ride the cliffside monorail through a building", "A night river cruise under the city's light show", "Authentic Chongqing hotpot, where mala was born"],
    whoFor: ["City and skyline lovers", "Food travelers chasing the real hotpot", "Travelers who like a private, flexible pace"],
    itinerary: [
      { day: 1, title: "Vertical city", summary: "Monorails, escalators and cliffside districts with a private guide.", highlights: ["Liziba monorail", "Hongya Cave at night"], meals: "Lunch", accommodation: "Riverside hotel" },
      { day: 2, title: "River & hotpot", summary: "Daytime river views, evening cruise and a hotpot dinner.", highlights: ["River cruise", "Hotpot dinner"], meals: "Breakfast", accommodation: "Riverside hotel" },
      { day: 3, title: "Backstreets & departure", summary: "A morning in the old quarters before your transfer.", highlights: ["Old quarter walk", "Airport transfer"], meals: "Breakfast" },
    ],
    included: ["2 nights riverside accommodation", "Private guide and driver", "Night river cruise", "One lunch and tickets"],
    notIncluded: ["Flights", "Visa", "Insurance", "Some meals", "Tips"],
    accommodation: "A riverside hotel with skyline views, central to the action.",
    transport: "Private vehicle, plus the city's monorail and a river cruise.",
    cancellation: "Free cancellation up to 14 days before. See booking conditions.",
    hostSlug: "lina",
    departures: [
      { date: "2026-07-04", status: "available", priceUSD: 540 },
      { date: "2026-09-05", status: "available", priceUSD: 560 },
      { date: "2026-10-03", status: "limited", priceUSD: 580 },
    ],
    faqs: [
      { question: "Is Chongqing walkable?", answer: "It's hilly and vertical, with lots of stairs and escalators. Your private pace means we adapt the routing to your fitness, and the driver covers the longer hops." },
    ],
  },
  {
    slug: "zhangjiajie-and-beyond",
    name: "Zhangjiajie & Beyond",
    category: "Mountains & Nature",
    style: "Small Group",
    tagline: "The floating pillars of Zhangjiajie, the waterfalls of Furong and the riverside lanes of Fenghuang — Hunan's wild side.",
    durationValue: 6,
    durationUnit: "days",
    route: ["Zhangjiajie", "Furong", "Fenghuang"],
    destinationSlugs: ["zhangjiajie"],
    travelStyleSlugs: ["mountains-nature", "small-group"],
    fromPriceUSD: 1390,
    rating: 4.88,
    reviewCount: 102,
    maxGroupSize: 12,
    activityLevel: "Active",
    soloFriendly: true,
    familyFriendly: true,
    departureMonths: [4, 5, 6, 9, 10],
    image: "tripZhangjiajie",
    gallery: ["tripZhangjiajie", "zhangjiajie"],
    bestSeller: false,
    customizable: true,
    highlights: ["The sandstone pillars that inspired floating-mountain film scenes", "A glass walkway and the world's highest outdoor lift", "An evening in the lantern-lit riverside town of Fenghuang"],
    whoFor: ["Active travelers and hikers", "Photographers", "Families with older children"],
    itinerary: [
      { day: 1, title: "Arrive Zhangjiajie", summary: "Settle in near the national park.", highlights: ["Welcome dinner"], meals: "Dinner", accommodation: "Park-side hotel" },
      { day: 2, title: "Forest park pillars", summary: "A full day among the famous sandstone columns.", highlights: ["Bailong elevator", "Avatar Hallelujah Mountain"], meals: "Breakfast, lunch", accommodation: "Park-side hotel" },
      { day: 3, title: "Glass bridge & canyon", summary: "Grand Canyon glass bridge and a walk below.", highlights: ["Glass bridge", "Canyon walk"], meals: "Breakfast", accommodation: "Park-side hotel" },
      { day: 4, title: "Furong waterfalls", summary: "Drive to the cliffside waterfall town of Furong.", highlights: ["Furong Town", "Waterfall views"], meals: "Breakfast", accommodation: "Riverside inn" },
      { day: 5, title: "Fenghuang old town", summary: "Continue to the riverside lanes of Fenghuang.", highlights: ["Stilt houses", "Evening lanterns"], meals: "Breakfast", accommodation: "Riverside inn" },
      { day: 6, title: "Departure", summary: "Transfer for onward travel.", highlights: ["Transfer"], meals: "Breakfast" },
    ],
    included: ["5 nights accommodation", "Private vehicle between sights", "English-speaking guide", "Park and cable-car tickets", "Daily breakfast and selected meals"],
    notIncluded: ["Flights or rail to Zhangjiajie", "Visa", "Insurance", "Some meals", "Tips"],
    accommodation: "A comfortable park-side hotel and a riverside inn in Fenghuang.",
    transport: "Private vehicle throughout, plus park shuttles, cable cars and the Bailong elevator.",
    cancellation: "Free cancellation up to 30 days before departure.",
    hostSlug: "mia",
    departures: [
      { date: "2026-04-18", status: "available", priceUSD: 1390 },
      { date: "2026-05-23", status: "limited", priceUSD: 1430 },
      { date: "2026-09-19", status: "available", priceUSD: 1450 },
      { date: "2026-10-10", status: "limited", priceUSD: 1490 },
    ],
    faqs: [
      { question: "How much walking is involved?", answer: "Expect several active days with stairs and uneven paths in the parks. Cable cars and lifts reduce the climbing, but good footwear is essential." },
    ],
  },
  {
    slug: "silk-road-west",
    name: "Silk Road West",
    category: "Ancient Culture",
    style: "Small Group",
    tagline: "Xi'an to Kashgar along the old Silk Road — Buddhist caves, desert oases and the great Sunday bazaar of the far west.",
    durationValue: 11,
    durationUnit: "days",
    route: ["Xi'an", "Lanzhou", "Dunhuang", "Turpan", "Kashgar"],
    destinationSlugs: ["xian", "xinjiang"],
    travelStyleSlugs: ["ancient-culture", "small-group"],
    fromPriceUSD: 3280,
    rating: 4.93,
    reviewCount: 78,
    maxGroupSize: 10,
    activityLevel: "Moderate",
    soloFriendly: true,
    familyFriendly: false,
    departureMonths: [5, 6, 9, 10],
    image: "tripSilkRoad",
    gallery: ["tripSilkRoad", "xinjiang", "xian"],
    bestSeller: false,
    customizable: true,
    highlights: ["The Mogao Grottoes — a thousand years of Buddhist cave art", "Singing-sand dunes and the crescent-moon oasis at Dunhuang", "Kashgar's old town and its legendary Sunday market"],
    whoFor: ["History and culture travelers", "Repeat visitors going deep", "Travelers comfortable with longer overland and rail days"],
    itinerary: [
      { day: 1, title: "Arrive Xi'an", summary: "The Silk Road's eastern start.", highlights: ["City wall"], meals: "Dinner", accommodation: "Design hotel" },
      { day: 2, title: "Warriors & departure point", summary: "Terracotta Warriors and the Great Mosque quarter.", highlights: ["Terracotta Army"], meals: "Breakfast", accommodation: "Design hotel" },
      { day: 3, title: "Rail to Lanzhou", summary: "Along the Yellow River.", highlights: ["High-speed rail", "Riverside walk"], meals: "Breakfast", accommodation: "City hotel" },
      { day: 4, title: "Bingling caves", summary: "A boat trip to cliffside Buddhist grottoes.", highlights: ["Bingling Temple"], meals: "Breakfast, lunch", accommodation: "City hotel" },
      { day: 5, title: "To Dunhuang", summary: "Travel into the desert oasis.", highlights: ["Overnight transit"], meals: "Breakfast", accommodation: "Desert hotel" },
      { day: 6, title: "Mogao Grottoes", summary: "The great cave galleries, then the dunes at sunset.", highlights: ["Mogao Grottoes", "Singing-sand dunes"], meals: "Breakfast", accommodation: "Desert hotel" },
      { day: 7, title: "To Turpan", summary: "Into China's hottest, lowest basin.", highlights: ["Rail journey", "Grape valley"], meals: "Breakfast", accommodation: "Oasis hotel" },
      { day: 8, title: "Turpan oases", summary: "Ancient karez irrigation and ruined cities.", highlights: ["Jiaohe ruins", "Karez wells"], meals: "Breakfast, lunch", accommodation: "Oasis hotel" },
      { day: 9, title: "To Kashgar", summary: "Fly far west to the edge of Central Asia.", highlights: ["Old town walk"], meals: "Breakfast", accommodation: "Old town hotel" },
      { day: 10, title: "Kashgar bazaar", summary: "The famous market and the old quarter's lanes.", highlights: ["Sunday market", "Id Kah square"], meals: "Breakfast", accommodation: "Old town hotel" },
      { day: 11, title: "Departure", summary: "Transfer for your onward flight.", highlights: ["Airport transfer"], meals: "Breakfast" },
    ],
    included: ["10 nights accommodation", "Rail, one internal flight and private drives", "Specialist guides", "Mogao and major site tickets", "Daily breakfast and selected meals"],
    notIncluded: ["International flights", "China visa and any regional permits", "Insurance", "Some meals", "Tips"],
    accommodation: "Comfortable city, desert and old-town hotels across the route.",
    transport: "A mix of high-speed rail, one internal flight to Kashgar, and private vehicles.",
    cancellation: "Free cancellation up to 45 days before departure due to permit and flight logistics.",
    hostSlug: "tashi",
    departures: [
      { date: "2026-05-16", status: "available", priceUSD: 3280 },
      { date: "2026-06-13", status: "limited", priceUSD: 3360 },
      { date: "2026-09-12", status: "available", priceUSD: 3420 },
      { date: "2026-10-03", status: "limited", priceUSD: 3480 },
    ],
    faqs: [
      { question: "Are special permits required?", answer: "Some far-western regions can require extra documentation that changes with current policy. We monitor requirements and handle what's needed once your booking is confirmed." },
      { question: "How long are the travel days?", answer: "A couple of legs are long by design — this is an overland Silk Road journey. We break them with stops and use rail and one flight to keep them comfortable." },
    ],
  },
  {
    slug: "tibet-roof-of-the-world",
    name: "Tibet: Roof of the World",
    category: "Ancient Culture",
    style: "Small Group",
    tagline: "Lhasa's great palaces, monastery debates and a sacred turquoise lake — the Himalayan plateau at a pace that lets you breathe.",
    durationValue: 7,
    durationUnit: "days",
    route: ["Lhasa", "Yamdrok Lake", "Gyantse"],
    destinationSlugs: ["tibet"],
    travelStyleSlugs: ["ancient-culture", "small-group", "mountains-nature"],
    fromPriceUSD: 2480,
    rating: 4.94,
    reviewCount: 88,
    maxGroupSize: 10,
    activityLevel: "Moderate",
    soloFriendly: true,
    familyFriendly: false,
    departureMonths: [4, 5, 6, 9, 10],
    image: "tripTibet",
    gallery: ["tripTibet", "tibet", "spotlightTibet"],
    bestSeller: true,
    customizable: true,
    highlights: [
      "The Potala Palace and the pilgrim-filled Jokhang Temple",
      "Monk debates at Sera Monastery",
      "A drive to sacred Yamdrok Lake, framed by snow peaks",
      "Careful altitude pacing with a licensed Tibetan guide throughout",
    ],
    whoFor: [
      "Culture and mountain travelers seeking something profound",
      "Those comfortable at high altitude (with time to acclimatize)",
      "Travelers who want the permits and logistics fully handled",
    ],
    itinerary: [
      { day: 1, title: "Arrive Lhasa — rest", summary: "Meet your guide and take it slow — the first day is for acclimatizing to 3,600m.", highlights: ["Gentle orientation", "Early night"], meals: "Dinner", accommodation: "Tibetan boutique hotel" },
      { day: 2, title: "Potala Palace & Jokhang", summary: "The former winter palace of the Dalai Lamas, then Tibet's holiest temple and the Barkhor kora.", highlights: ["Potala Palace", "Jokhang Temple", "Barkhor circuit"], meals: "Breakfast", accommodation: "Tibetan boutique hotel" },
      { day: 3, title: "Sera & Drepung monasteries", summary: "Two of the great monasteries, including the famous afternoon monk debates at Sera.", highlights: ["Sera monk debates", "Drepung Monastery"], meals: "Breakfast, lunch", accommodation: "Tibetan boutique hotel" },
      { day: 4, title: "Yamdrok Lake", summary: "A spectacular drive over a high pass to the sacred turquoise lake.", highlights: ["Kamba La pass", "Yamdrok Lake"], meals: "Breakfast", accommodation: "Tibetan boutique hotel" },
      { day: 5, title: "Toward Gyantse", summary: "Continue across the plateau to the historic town of Gyantse and its tiered Kumbum stupa.", highlights: ["Gyantse Kumbum", "Plateau scenery"], meals: "Breakfast", accommodation: "Plateau guesthouse" },
      { day: 6, title: "Return to Lhasa", summary: "A scenic return with time for a final wander through the old town.", highlights: ["Old town free time"], meals: "Breakfast", accommodation: "Tibetan boutique hotel" },
      { day: 7, title: "Departure", summary: "Transfer to the station or airport for your onward journey.", highlights: ["Transfer"], meals: "Breakfast" },
    ],
    included: ["6 nights accommodation", "Tibet Travel Permit and arrangements", "Licensed Tibetan guide throughout", "Private vehicle and driver", "Listed monastery and site tickets", "Daily breakfast and selected meals"],
    notIncluded: ["Flights or rail to Lhasa", "China visa", "Travel insurance (required)", "Some meals", "Tips"],
    accommodation: "A characterful Tibetan boutique hotel in Lhasa and a comfortable guesthouse in Gyantse.",
    transport: "Private vehicle across the plateau with a licensed guide; high-altitude railway or flight to reach Lhasa.",
    cancellation: "Free cancellation up to 45 days before departure due to permit lead times. See booking conditions.",
    hostSlug: "tashi",
    departures: [
      { date: "2026-05-16", status: "available", priceUSD: 2480 },
      { date: "2026-06-13", status: "limited", priceUSD: 2540 },
      { date: "2026-09-12", status: "available", priceUSD: 2580 },
      { date: "2026-10-10", status: "limited", priceUSD: 2640 },
    ],
    faqs: [
      { question: "How high is Tibet, and is it safe?", answer: "Lhasa sits above 3,600m. We keep the first day very gentle to help you acclimatize, and your guide watches for altitude symptoms. Talk to your doctor before booking, especially with heart or lung conditions." },
      { question: "Do I need a special permit?", answer: "Yes — Tibet requires a Tibet Travel Permit arranged in advance, and you must travel with a licensed guide. We handle the current permit requirements once your booking is confirmed." },
    ],
  },
  {
    slug: "chengdu-and-pandas",
    name: "Chengdu & Pandas",
    category: "Slow & Local",
    style: "Small Group",
    tagline: "Giant pandas at dawn, tea houses by afternoon and hotpot after dark — the most relaxed four days in China.",
    durationValue: 4,
    durationUnit: "days",
    route: ["Chengdu"],
    destinationSlugs: ["chengdu"],
    travelStyleSlugs: ["slow-local", "small-group", "food-nightlife"],
    fromPriceUSD: 720,
    rating: 4.92,
    reviewCount: 176,
    maxGroupSize: 10,
    activityLevel: "Easy",
    soloFriendly: true,
    familyFriendly: true,
    departureMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    image: "tripChengdu",
    gallery: ["tripChengdu", "chengdu", "reviewPanda"],
    bestSeller: true,
    customizable: true,
    highlights: [
      "The giant panda base at dawn, when the pandas are most active",
      "A hands-on Sichuan cooking session with a local host",
      "Tea-house culture, ear-cleaners and slow afternoons",
      "A guided hotpot night — the birthplace of mala",
    ],
    whoFor: [
      "First-timers who want a gentle, food-led introduction to China",
      "Families (this is one of our most family-friendly trips)",
      "Anyone who wants to see pandas the right way",
    ],
    itinerary: [
      { day: 1, title: "Arrive Chengdu", summary: "Settle in and take an easy evening stroll through the snack streets with your host.", highlights: ["Jinli snack street", "Welcome dinner"], meals: "Dinner", accommodation: "Central boutique hotel" },
      { day: 2, title: "Pandas at dawn", summary: "An early start at the panda base to see them at their liveliest, then a relaxed afternoon.", highlights: ["Giant panda base", "Tea house afternoon"], meals: "Breakfast", accommodation: "Central boutique hotel" },
      { day: 3, title: "Cook & eat Sichuan", summary: "A market visit and hands-on cooking class, then a guided hotpot night.", highlights: ["Sichuan cooking class", "Hotpot night"], meals: "Breakfast, lunch", accommodation: "Central boutique hotel" },
      { day: 4, title: "Old temples & departure", summary: "A calm morning at Wenshu Monastery before your onward transfer.", highlights: ["Wenshu Monastery", "Transfer"], meals: "Breakfast" },
    ],
    included: ["3 nights central accommodation", "English-speaking local host", "Panda base and site tickets", "Cooking class and hotpot dinner", "Daily breakfast and selected meals", "Airport/station transfers"],
    notIncluded: ["Flights or rail to Chengdu", "China visa", "Travel insurance", "Some meals", "Tips"],
    accommodation: "A central boutique hotel within easy reach of Chengdu's tea houses and snack streets.",
    transport: "Private vehicle for the panda base and transfers; walkable, metro-friendly city otherwise.",
    cancellation: "Free cancellation up to 14 days before departure. See booking conditions.",
    hostSlug: "lina",
    departures: [
      { date: "2026-06-29", status: "available", priceUSD: 720 },
      { date: "2026-07-06", status: "available", priceUSD: 720 },
      { date: "2026-09-07", status: "limited", priceUSD: 740 },
      { date: "2026-10-05", status: "available", priceUSD: 760 },
    ],
    faqs: [
      { question: "What time do we see the pandas?", answer: "We go early, right around opening, because pandas are most active in the cool morning and the base gets busy later. It's an early start but well worth it." },
      { question: "Is this good for kids?", answer: "Yes — it's one of our most family-friendly trips. The pace is easy, the pandas are a hit, and spice levels at meals are always adjustable." },
    ],
  },
];

export function getAllTrips(): Trip[] {
  return trips;
}

export function getTripBySlug(slug: string): Trip | undefined {
  return trips.find((t) => t.slug === slug);
}

export function getBestSellerTrips(): Trip[] {
  return trips.filter((t) => t.bestSeller);
}

export function getTripsByDestination(slug: string): Trip[] {
  return trips.filter((t) => t.destinationSlugs.includes(slug));
}

export function getTripsByTravelStyle(slug: string): Trip[] {
  return trips.filter((t) => t.travelStyleSlugs.includes(slug));
}

export function getRelatedTrips(trip: Trip, limit = 3): Trip[] {
  return trips
    .filter((t) => t.slug !== trip.slug)
    .map((t) => ({
      t,
      score:
        t.destinationSlugs.filter((d) => trip.destinationSlugs.includes(d)).length * 2 +
        t.travelStyleSlugs.filter((s) => trip.travelStyleSlugs.includes(s)).length,
    }))
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((x) => x.t);
}
